const jSuites = require('../dist/jsuites');

describe('jSuites mask', () => {
    describe('keydown events', () => {
        test('0.00', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="0.00">';
            let input = document.getElementById('test-input')
            const event = new InputEvent('input', { bubbles: true, cancelable: true });

            input.value = '7581003';
            input.dispatchEvent(event);
            expect(input.value).toEqual('7581003');
            input.value = '.03';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0.03');
            input.value = '-.03';
            input.dispatchEvent(event);
            expect(input.value).toEqual('-0,03');
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '00';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '000000000';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '01';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '00000001';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '7581003.00003';
            input.dispatchEvent(event);
            expect(input.value).toEqual('7581003.00003');
            input.value = '-7581003.00003';
            input.dispatchEvent(event);
            expect(input.value).toEqual('-7581003.00003');
            input.value = '7581003.000-03';
            input.dispatchEvent(event);
            expect(input.value).toEqual('-7581003.00003');
            input.value = '7581-003.00003';
            input.dispatchEvent(event);
            expect(input.value).toEqual('-7581003.00003');
            input.value = '123abcde';
            input.dispatchEvent(event);
            expect(input.value).toEqual('123');
            input.value = '';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('0,00', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="0,00">';
            let input = document.getElementById('test-input')
            const event = new InputEvent('input', { bubbles: true, cancelable: true });

            input.value = '7581003';
            input.dispatchEvent(event);
            expect(input.value).toEqual('7581003');
            input.value = ',03';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0,03');
            input.value = '-,03';
            input.dispatchEvent(event);
            expect(input.value).toEqual('-0,03');
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '00';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '000000000';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '01';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '00000001';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '7581003,00003';
            input.dispatchEvent(event);
            expect(input.value).toEqual('7581003,00003');
            input.value = '-7581003,00003';
            input.dispatchEvent(event);
            expect(input.value).toEqual('-7581003,00003');
            input.value = '7581003,000-03';
            input.dispatchEvent(event);
            expect(input.value).toEqual('-7581003,00003');
            input.value = '7581-003,00003';
            input.dispatchEvent(event);
            expect(input.value).toEqual('-7581003,00003');
            input.value = '123abcde';
            input.dispatchEvent(event);
            expect(input.value).toEqual('123');
            input.value = '';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('0%', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="0%">';
            let input = document.getElementById('test-input')
            const event = new InputEvent('input', { bubbles: true, cancelable: true });

            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0%');
            input.value = '';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '7';
            input.dispatchEvent(event);
            expect(input.value).toEqual('7%');
            input.value = '54';
            input.dispatchEvent(event);
            expect(input.value).toEqual('54%');
            input.value = '100';
            input.dispatchEvent(event);
            expect(input.value).toEqual('100%');
            input.value = '100.0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('100.0%');
            input.value = '764';
            input.dispatchEvent(event);
            expect(input.value).toEqual('764%');
            input.value = '124577';
            input.dispatchEvent(event);
            expect(input.value).toEqual('124577%');
            input.value = '123abcde';
            input.dispatchEvent(event);
            expect(input.value).toEqual('123%');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('0.00%', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="0.00%">';
            let input = document.getElementById('test-input')
            const event = new InputEvent('input', { bubbles: true, cancelable: true });

            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0%');
            input.value = '';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '7';
            input.dispatchEvent(event);
            expect(input.value).toEqual('7%');
            input.value = '54';
            input.dispatchEvent(event);
            expect(input.value).toEqual('54%');
            input.value = '100';
            input.dispatchEvent(event);
            expect(input.value).toEqual('100%');
            input.value = '100.0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('100.0%');
            input.value = '764';
            input.dispatchEvent(event);
            expect(input.value).toEqual('764%');
            input.value = '124577';
            input.dispatchEvent(event);
            expect(input.value).toEqual('124577%');
            input.value = '123abcde';
            input.dispatchEvent(event);
            expect(input.value).toEqual('123%');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('#,##0.00', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="#,##0.00">';
            let input = document.getElementById('test-input')
            const event = new InputEvent('input', { bubbles: true, cancelable: true });

            input.value = '7581003';
            input.dispatchEvent(event);
            expect(input.value).toEqual('7,581,003');
            input.value = '75810.03';
            input.dispatchEvent(event);
            expect(input.value).toEqual('75,810.03');
            input.value = '9876543210';
            input.dispatchEvent(event);
            expect(input.value).toEqual('9,876,543,210');
            input.value = '1234567890.99';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1,234,567,890.99');
            input.value = '1234';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1,234');
            input.value = '100';
            input.dispatchEvent(event);
            expect(input.value).toEqual('100');
            input.value = '100.5';
            input.dispatchEvent(event);
            expect(input.value).toEqual('100.5');
            input.value = '';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '-5000';
            input.dispatchEvent(event);
            expect(input.value).toEqual('-5,000');
            input.value = '-5000.75';
            input.dispatchEvent(event);
            expect(input.value).toEqual('-5,000.75');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('#.##0,00', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="#.##0,00">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '7581003';
            input.dispatchEvent(event);
            expect(input.value).toEqual('7.581.003');
            input.value = '75810,03';
            input.dispatchEvent(event);
            expect(input.value).toEqual('75.810,03');
            input.value = '9876543210';
            input.dispatchEvent(event);
            expect(input.value).toEqual('9.876.543.210');
            input.value = '1234567890,99';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1.234.567.890,99');
            input.value = '1234';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1.234');
            input.value = '100,5';
            input.dispatchEvent(event);
            expect(input.value).toEqual('100,5');
            input.value = '';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '-5000';
            input.dispatchEvent(event);
            expect(input.value).toEqual('-5.000');
            input.value = '-5000,75';
            input.dispatchEvent(event);
            expect(input.value).toEqual('-5.000,75');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });  

        test('$ #,##0.00', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="$ #,##0.00">';
            let input = document.getElementById('test-input')
            const event = new InputEvent('input', { bubbles: true, cancelable: true });

            input.value = '7581003';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 7,581,003');
            input.value = '75810.03';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 75,810.03');
            input.value = '9876543210';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 9,876,543,210');
            input.value = '1234567890.99';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 1,234,567,890.99');
            input.value = '1234';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 1,234');
            input.value = '100';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 100');
            input.value = '100.5';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 100.5');
            input.value = '';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 0');
            input.value = '-5000';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ -5,000');
            input.value = '-5000.75';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ -5,000.75');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ ');
        });

        test('$ #.##0,00', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="$ #.##0,00">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '7581003';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 7.581.003');
            input.value = '75810,03';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 75.810,03');
            input.value = '9876543210';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 9.876.543.210');
            input.value = '1234567890,99';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 1.234.567.890,99');
            input.value = '1234';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 1.234');
            input.value = '100,5';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 100,5');
            input.value = '';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 0');
            input.value = '-5000';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ -5.000');
            input.value = '-5000,75';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ -5.000,75');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ ');
        });

        test('D', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="dd">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '4';
            input.dispatchEvent(event);
            expect(input.value).toEqual('04');
            input.value = '10';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '20';
            input.dispatchEvent(event);
            expect(input.value).toEqual('20');
            input.value = '30';
            input.dispatchEvent(event);
            expect(input.value).toEqual('30');
            input.value = '31';
            input.dispatchEvent(event);
            expect(input.value).toEqual('31');
            input.value = '32';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '36';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '1.0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '-3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('DD', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="dd">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '4';
            input.dispatchEvent(event);
            expect(input.value).toEqual('04');
            input.value = '10';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '20';
            input.dispatchEvent(event);
            expect(input.value).toEqual('20');
            input.value = '30';
            input.dispatchEvent(event);
            expect(input.value).toEqual('30');
            input.value = '31';
            input.dispatchEvent(event);
            expect(input.value).toEqual('31');
            input.value = '32';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '36';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '1.0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '-3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('DDD', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="ddd">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '4';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '10';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '20';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = 'm';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Mon');
            input.value = 't';
            input.dispatchEvent(event);
            expect(input.value).toEqual('t');
            input.value = 't abcdefgijklmnopqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('t');
            input.value = 'tu';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Tue');
            input.value = 'th';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Thu');
            input.value = 'w';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Wed');
            input.value = 'f';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Fri');
            input.value = 's';
            input.dispatchEvent(event);
            expect(input.value).toEqual('s');
            input.value = 's bcdefghijklmnopqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('s');
            input.value = 'sa';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Sat');
            input.value = 'su';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Sun');
            input.value = 'abcdeghijklnopqruvxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '-';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('DDDD', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="dddd">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '4';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '10';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '20';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = 'm';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Monday');
            input.value = 't';
            input.dispatchEvent(event);
            expect(input.value).toEqual('t');
            input.value = 't abcdefgijklmnopqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('t');
            input.value = 'tu';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Tuesday');
            input.value = 'th';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Thursday');
            input.value = 'w';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Wednesday');
            input.value = 'f';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Friday');
            input.value = 's';
            input.dispatchEvent(event);
            expect(input.value).toEqual('s');
            input.value = 's bcdefghijklmnopqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('s');
            input.value = 'sa';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Saturday');
            input.value = 'su';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Sunday');
            input.value = 'abcdeghijklnopqruvxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '-';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('DY', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="dy">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '4';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '10';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '20';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = 'm';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Mon');
            input.value = 't';
            input.dispatchEvent(event);
            expect(input.value).toEqual('t');
            input.value = 't abcdefgijklmnopqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('t');
            input.value = 'tu';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Tue');
            input.value = 'th';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Thu');
            input.value = 'w';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Wed');
            input.value = 'f';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Fri');
            input.value = 's';
            input.dispatchEvent(event);
            expect(input.value).toEqual('s');
            input.value = 's bcdefghijklmnopqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('s');
            input.value = 'sa';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Sat');
            input.value = 'su';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Sun');
            input.value = 'abcdeghijklnopqruvxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '-';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('DAY', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="day">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '4';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '10';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '20';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = 'm';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Monday');
            input.value = 't';
            input.dispatchEvent(event);
            expect(input.value).toEqual('t');
            input.value = 't abcdefgijklmnopqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('t');
            input.value = 'tu';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Tuesday');
            input.value = 'th';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Thursday');
            input.value = 'w';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Wednesday');
            input.value = 'f';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Friday');
            input.value = 's';
            input.dispatchEvent(event);
            expect(input.value).toEqual('s');
            input.value = 's bcdefghijklmnopqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('s');
            input.value = 'sa';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Saturday');
            input.value = 'su';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Sunday');
            input.value = 'abcdeghijklnopqruvxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '-';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('WD', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="wd">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '4';
            input.dispatchEvent(event);
            expect(input.value).toEqual('4');
            input.value = '6';
            input.dispatchEvent(event);
            expect(input.value).toEqual('6');
            input.value = '7';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '8';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '10';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '11';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '30';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '1.0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '-3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = 'abcdefghijklmnopqrstuvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('M', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="mm">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('02');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('03');
            input.value = '4';
            input.dispatchEvent(event);
            expect(input.value).toEqual('04');
            input.value = '10';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '11';
            input.dispatchEvent(event);
            expect(input.value).toEqual('11');
            input.value = '12';
            input.dispatchEvent(event);
            expect(input.value).toEqual('12');
            input.value = '13';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '14';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '15';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '1.0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '1,0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '-1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '-11';
            input.dispatchEvent(event);
            expect(input.value).toEqual('11');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('MM', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="mm">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('02');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('03');
            input.value = '4';
            input.dispatchEvent(event);
            expect(input.value).toEqual('04');
            input.value = '10';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '11';
            input.dispatchEvent(event);
            expect(input.value).toEqual('11');
            input.value = '12';
            input.dispatchEvent(event);
            expect(input.value).toEqual('12');
            input.value = '13';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '14';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '15';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '1.0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '1,0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '-1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '-11';
            input.dispatchEvent(event);
            expect(input.value).toEqual('11');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('MMM', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="mmm">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '11';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '99';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '111';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = 'J';
            input.dispatchEvent(event);
            expect(input.value).toEqual('J');
            input.value = 'j';
            input.dispatchEvent(event);
            expect(input.value).toEqual('j');
            input.value = 'j bcdefghijklmnopqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('j');
            input.value = 'ja';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Jan');
            input.value = 'ju';
            input.dispatchEvent(event);
            expect(input.value).toEqual('ju');
            input.value = 'jun';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Jun');
            input.value = 'jul';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Jul');
            input.value = 'f';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Feb');
            input.value = 'm';
            input.dispatchEvent(event);
            expect(input.value).toEqual('m');
            input.value = 'ma';
            input.dispatchEvent(event);
            expect(input.value).toEqual('ma');
            input.value = 'ma abcdefghijklmnopqstuvwxz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('ma');
            input.value = 'mar';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Mar');
            input.value = 'may';
            input.dispatchEvent(event);
            expect(input.value).toEqual('May');
            input.value = 'a';
            input.dispatchEvent(event);
            expect(input.value).toEqual('a');
            input.value = 'a abcdefghijklmnoqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('a');
            input.value = 'ap';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Apr');
            input.value = 'au';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Aug');
            input.value = 's';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Sep');
            input.value = 'o';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Oct');
            input.value = 'n';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Nov');
            input.value = 'd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Dec');
            input.value = 'bceghiklpqrtuvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '-';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('MMMM', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="mmmm">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '11';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '99';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '111';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = 'J';
            input.dispatchEvent(event);
            expect(input.value).toEqual('J');
            input.value = 'j';
            input.dispatchEvent(event);
            expect(input.value).toEqual('j');
            input.value = 'j bcdefghijklmnopqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('j');
            input.value = 'ja';
            input.dispatchEvent(event);
            expect(input.value).toEqual('January');
            input.value = 'ju';
            input.dispatchEvent(event);
            expect(input.value).toEqual('ju');
            input.value = 'jun';
            input.dispatchEvent(event);
            expect(input.value).toEqual('June');
            input.value = 'jul';
            input.dispatchEvent(event);
            expect(input.value).toEqual('July');
            input.value = 'f';
            input.dispatchEvent(event);
            expect(input.value).toEqual('February');
            input.value = 'm';
            input.dispatchEvent(event);
            expect(input.value).toEqual('m');
            input.value = 'ma';
            input.dispatchEvent(event);
            expect(input.value).toEqual('ma');
            input.value = 'ma abcdefghijklmnopqstuvwxz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('ma');
            input.value = 'mar';
            input.dispatchEvent(event);
            expect(input.value).toEqual('March');
            input.value = 'may';
            input.dispatchEvent(event);
            expect(input.value).toEqual('May');
            input.value = 'a';
            input.dispatchEvent(event);
            expect(input.value).toEqual('a');
            input.value = 'a abcdefghijklmnoqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('a');
            input.value = 'ap';
            input.dispatchEvent(event);
            expect(input.value).toEqual('April');
            input.value = 'au';
            input.dispatchEvent(event);
            expect(input.value).toEqual('August');
            input.value = 's';
            input.dispatchEvent(event);
            expect(input.value).toEqual('September');
            input.value = 'o';
            input.dispatchEvent(event);
            expect(input.value).toEqual('October');
            input.value = 'n';
            input.dispatchEvent(event);
            expect(input.value).toEqual('November');
            input.value = 'd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('December');
            input.value = 'bceghiklpqrtuvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '-';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('MON', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="mon">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '11';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '99';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '111';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = 'J';
            input.dispatchEvent(event);
            expect(input.value).toEqual('J');
            input.value = 'j';
            input.dispatchEvent(event);
            expect(input.value).toEqual('j');
            input.value = 'j bcdefghijklmnopqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('j');
            input.value = 'ja';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Jan');
            input.value = 'ju';
            input.dispatchEvent(event);
            expect(input.value).toEqual('ju');
            input.value = 'jun';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Jun');
            input.value = 'jul';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Jul');
            input.value = 'f';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Feb');
            input.value = 'm';
            input.dispatchEvent(event);
            expect(input.value).toEqual('m');
            input.value = 'ma';
            input.dispatchEvent(event);
            expect(input.value).toEqual('ma');
            input.value = 'ma abcdefghijklmnopqstuvwxz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('ma');
            input.value = 'mar';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Mar');
            input.value = 'may';
            input.dispatchEvent(event);
            expect(input.value).toEqual('May');
            input.value = 'a';
            input.dispatchEvent(event);
            expect(input.value).toEqual('a');
            input.value = 'a abcdefghijklmnoqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('a');
            input.value = 'ap';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Apr');
            input.value = 'au';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Aug');
            input.value = 's';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Sep');
            input.value = 'o';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Oct');
            input.value = 'n';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Nov');
            input.value = 'd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Dec');
            input.value = 'bceghiklpqrtuvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '-';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('MONTH', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="month">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '11';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '99';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '111';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = 'J';
            input.dispatchEvent(event);
            expect(input.value).toEqual('J');
            input.value = 'j';
            input.dispatchEvent(event);
            expect(input.value).toEqual('j');
            input.value = 'j bcdefghijklmnopqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('j');
            input.value = 'ja';
            input.dispatchEvent(event);
            expect(input.value).toEqual('January');
            input.value = 'ju';
            input.dispatchEvent(event);
            expect(input.value).toEqual('ju');
            input.value = 'jun';
            input.dispatchEvent(event);
            expect(input.value).toEqual('June');
            input.value = 'jul';
            input.dispatchEvent(event);
            expect(input.value).toEqual('July');
            input.value = 'f';
            input.dispatchEvent(event);
            expect(input.value).toEqual('February');
            input.value = 'm';
            input.dispatchEvent(event);
            expect(input.value).toEqual('m');
            input.value = 'ma';
            input.dispatchEvent(event);
            expect(input.value).toEqual('ma');
            input.value = 'ma abcdefghijklmnopqstuvwxz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('ma');
            input.value = 'mar';
            input.dispatchEvent(event);
            expect(input.value).toEqual('March');
            input.value = 'may';
            input.dispatchEvent(event);
            expect(input.value).toEqual('May');
            input.value = 'a';
            input.dispatchEvent(event);
            expect(input.value).toEqual('a');
            input.value = 'a abcdefghijklmnoqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('a');
            input.value = 'ap';
            input.dispatchEvent(event);
            expect(input.value).toEqual('April');
            input.value = 'au';
            input.dispatchEvent(event);
            expect(input.value).toEqual('August');
            input.value = 's';
            input.dispatchEvent(event);
            expect(input.value).toEqual('September');
            input.value = 'o';
            input.dispatchEvent(event);
            expect(input.value).toEqual('October');
            input.value = 'n';
            input.dispatchEvent(event);
            expect(input.value).toEqual('November');
            input.value = 'd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('December');
            input.value = 'bceghiklpqrtuvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '-';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('YY', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="yy">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '99';
            input.dispatchEvent(event);
            expect(input.value).toEqual('99');
            input.value = '100';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '2024';
            input.dispatchEvent(event);
            expect(input.value).toEqual('20');
            input.value = '2.1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('21');
            input.value = '-99';
            input.dispatchEvent(event);
            expect(input.value).toEqual('99');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '-';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('YYY', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="yyy">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '4';
            input.dispatchEvent(event);
            expect(input.value).toEqual('4');
            input.value = '10';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '11';
            input.dispatchEvent(event);
            expect(input.value).toEqual('11');
            input.value = '12';
            input.dispatchEvent(event);
            expect(input.value).toEqual('12');
            input.value = '13';
            input.dispatchEvent(event);
            expect(input.value).toEqual('13');
            input.value = '14';
            input.dispatchEvent(event);
            expect(input.value).toEqual('14');
            input.value = '15';
            input.dispatchEvent(event);
            expect(input.value).toEqual('15');
            input.value = '999';
            input.dispatchEvent(event);
            expect(input.value).toEqual('999');
            input.value = '2001';
            input.dispatchEvent(event);
            expect(input.value).toEqual('200');
            input.value = '2024';
            input.dispatchEvent(event);
            expect(input.value).toEqual('202');
            input.value = '2999';
            input.dispatchEvent(event);
            expect(input.value).toEqual('299');
            input.value = '3001';
            input.dispatchEvent(event);
            expect(input.value).toEqual('300');
            input.value = '980213124124124981723987123';
            input.dispatchEvent(event);
            expect(input.value).toEqual('980');
            input.value = '20245';
            input.dispatchEvent(event);
            expect(input.value).toEqual('202');
            input.value = '202432423532';
            input.dispatchEvent(event);
            expect(input.value).toEqual('202');
            input.value = '9abcdfwerrdwef10';
            input.dispatchEvent(event);
            expect(input.value).toEqual('910');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '9.9.9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('999');
            input.value = '9,9,9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('999');
            input.value = '-';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('YYYY', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="yyyy">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '4';
            input.dispatchEvent(event);
            expect(input.value).toEqual('4');
            input.value = '10';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '11';
            input.dispatchEvent(event);
            expect(input.value).toEqual('11');
            input.value = '12';
            input.dispatchEvent(event);
            expect(input.value).toEqual('12');
            input.value = '13';
            input.dispatchEvent(event);
            expect(input.value).toEqual('13');
            input.value = '14';
            input.dispatchEvent(event);
            expect(input.value).toEqual('14');
            input.value = '15';
            input.dispatchEvent(event);
            expect(input.value).toEqual('15');
            input.value = '1999';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1999');
            input.value = '2001';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2001');
            input.value = '2024';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2024');
            input.value = '2999';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2999');
            input.value = '3001';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3001');
            input.value = '20245';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2024');
            input.value = '202432423532';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2024');
            input.value = '20abcdfwerrdwef24';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2024');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '1.9.9.9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1999');
            input.value = '1,9,9,9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1999');
            input.value = '-';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('H', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="h">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('9');
            input.value = '12';
            input.dispatchEvent(event);
            expect(input.value).toEqual('12');
            input.value = '19';
            input.dispatchEvent(event);
            expect(input.value).toEqual('19');
            input.value = '25';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2');
            input.value = '30';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '40';
            input.dispatchEvent(event);
            expect(input.value).toEqual('4');
            input.value = '90';
            input.dispatchEvent(event);
            expect(input.value).toEqual('9');
            input.value = '100';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '111';
            input.dispatchEvent(event);
            expect(input.value).toEqual('11');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '-3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '1.2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('12');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('HH', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="hh">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('03');
            input.value = '9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('09');
            input.value = '12';
            input.dispatchEvent(event);
            expect(input.value).toEqual('12');
            input.value = '1.2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('12');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '-';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('HH24', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="hh24">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('9');
            input.value = '12';
            input.dispatchEvent(event);
            expect(input.value).toEqual('12');
            input.value = '19';
            input.dispatchEvent(event);
            expect(input.value).toEqual('19');
            input.value = '25';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2');
            input.value = '30';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '40';
            input.dispatchEvent(event);
            expect(input.value).toEqual('4');
            input.value = '90';
            input.dispatchEvent(event);
            expect(input.value).toEqual('9');
            input.value = '100';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '111';
            input.dispatchEvent(event);
            expect(input.value).toEqual('11');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '-3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '1.2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('12');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('MI', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="mi">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '4';
            input.dispatchEvent(event);
            expect(input.value).toEqual('4');
            input.value = '5';
            input.dispatchEvent(event);
            expect(input.value).toEqual('5');
            input.value = '6';
            input.dispatchEvent(event);
            expect(input.value).toEqual('06');
            input.value = '7';
            input.dispatchEvent(event);
            expect(input.value).toEqual('07');
            input.value = '8';
            input.dispatchEvent(event);
            expect(input.value).toEqual('08');
            input.value = '9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('09');
            input.value = '51';
            input.dispatchEvent(event);
            expect(input.value).toEqual('51');
            input.value = '52';
            input.dispatchEvent(event);
            expect(input.value).toEqual('52');
            input.value = '58';
            input.dispatchEvent(event);
            expect(input.value).toEqual('58');
            input.value = '59';
            input.dispatchEvent(event);
            expect(input.value).toEqual('59');
            input.value = '5555555555555';
            input.dispatchEvent(event);
            expect(input.value).toEqual('55');
            input.value = '9999999999999999';
            input.dispatchEvent(event);
            expect(input.value).toEqual('09');
            input.value = '-1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '1.2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('12');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('SS', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="ss">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '4';
            input.dispatchEvent(event);
            expect(input.value).toEqual('4');
            input.value = '5';
            input.dispatchEvent(event);
            expect(input.value).toEqual('5');
            input.value = '6';
            input.dispatchEvent(event);
            expect(input.value).toEqual('06');
            input.value = '7';
            input.dispatchEvent(event);
            expect(input.value).toEqual('07');
            input.value = '8';
            input.dispatchEvent(event);
            expect(input.value).toEqual('08');
            input.value = '9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('09');
            input.value = '51';
            input.dispatchEvent(event);
            expect(input.value).toEqual('51');
            input.value = '52';
            input.dispatchEvent(event);
            expect(input.value).toEqual('52');
            input.value = '58';
            input.dispatchEvent(event);
            expect(input.value).toEqual('58');
            input.value = '59';
            input.dispatchEvent(event);
            expect(input.value).toEqual('59');
            input.value = '5555555555555';
            input.dispatchEvent(event);
            expect(input.value).toEqual('55');
            input.value = '9999999999999999';
            input.dispatchEvent(event);
            expect(input.value).toEqual('09');
            input.value = '-1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '1.2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('12');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('AM/PM', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="AM/PM">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '5';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '8';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '123456789.!@#$%^&*()-';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = 'A';
            input.dispatchEvent(event);
            expect(input.value).toEqual('A');
            input.value = 'P';
            input.dispatchEvent(event);
            expect(input.value).toEqual('P');
            input.value = 'AM';
            input.dispatchEvent(event);
            expect(input.value).toEqual('AM');
            input.value = 'PM';
            input.dispatchEvent(event);
            expect(input.value).toEqual('PM');
            input.value = 'BCDEFGHIJKLNOQRSTUVWXYZ';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = 'M';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });
    });

    // describe('render method', () => {
    //     test('decimals', () => {
    //         expect(jSuites.mask.render(123.456789, { mask: '000.00' }, true).value).toEqual("123.46");
    //         expect(jSuites.mask.render(123.456, { mask: '000.0' }, true).value).toEqual("123.46");
    //         expect(jSuites.mask.render(789.123, { mask: '000.00' }, true).value).toEqual("789.12");
    //         expect(jSuites.mask.render(456.78, { mask: '000.00' }, true).value).toEqual("456.78");
    //     });
    
    //     test('padding', () => {
    //         expect(jSuites.mask.render(123, { mask: '00000' }, true).value).toEqual("00123");
    //         expect(jSuites.mask.render(9876.54321, { mask: '00000' }, true).value).toEqual("09877");
    //         expect(jSuites.mask.render(1.2, { mask: '0.000' }, true).value).toEqual("1.200");
    //         expect(jSuites.mask.render(12, { mask: '00' }, true).value).toEqual("12");
    //     });
    
    //     test('padding decimals', () => {
    //         expect(jSuites.mask.render(123.23, { mask: '000.000' }, true).value).toEqual("123.230");
    //         expect(jSuites.mask.render(789.1, { mask: '000.000' }, true).value).toEqual("789.100");
    //     });
    
    //     test('numeric', () => {
    //         expect(jSuites.mask.render(123.2332, { mask: '00000.00'}, true).value).toEqual("00123.23");    
    //         expect(jSuites.mask.render(1.2, { mask: '000000.000' }, true).value).toEqual("000001.200");
    //         expect(jSuites.mask.render(-45.67, { mask: '00000.00' }, true).value).toEqual("-00045.67");
    
    //         expect(jSuites.mask.render(12345.678, { mask: '#,##0.00' }, true).value).toEqual("12,345.68");
    //         expect(jSuites.mask.render(987654.321, { mask: '#,##0.00' }, true).value).toEqual("987,654.32");
    //         expect(jSuites.mask.render(54321, { mask: '#,##0' }, true).value).toEqual("54,321");
    
    //         expect(jSuites.mask.render(0, { mask: '000.00' }, true).value).toEqual("000.00");
    //         expect(jSuites.mask.render(123456789, { mask: '0000000000' }, true).value).toEqual("0123456789");
    //     });
    
    //     test('edge cases', () => {
    //         expect(jSuites.mask.render(0, { mask: '0.00' }, true).value).toEqual("0.00");
    //         expect(jSuites.mask.render(0.123, { mask: '0.00' }, true).value).toEqual("0.12");
    //         expect(jSuites.mask.render(-456, { mask: '000' }, true).value).toEqual("-456");
    //         expect(jSuites.mask.render(1000, { mask: '0,000' }, true).value).toEqual("1,000");
    //     });
    // })
});
