const jSuites = require('../dist/jsuites');

describe('jSuites mask', () => {

    test('jSuites.mask.render', () => {
        expect(jSuites.mask.render(123, { mask: '00000' }, true)).toBe('00123');
        expect(jSuites.mask.render(0.128899, { mask: '$ #.##0,00' }, true)).toBe('$ 0,13');
        expect(jSuites.mask.render(0.1, { mask: '0%' }, true)).toBe('10%');
        expect(jSuites.mask.render(1.005, { mask: '0.00' }, true)).toBe('1.01');
        expect(jSuites.mask.render(11.45, { mask: '0.0' }, true)).toBe('11.5');
        expect(jSuites.mask.render(-11.45, { mask: '0.0' }, true)).toBe('-11.5');
        expect(jSuites.mask.render(1000000.0005, { mask: '0.000' }, true)).toBe('1000000.001');
        expect(jSuites.mask.render(-1000000.0005, { mask: '0.000' }, true)).toBe('-1000000.001');
        expect(jSuites.mask.render(-11.449, { mask: '0.00' }, true)).toBe('-11.45');
        expect(jSuites.mask.render(-11.455, { mask: '0.00' }, true)).toBe('-11.46');
        expect(jSuites.mask.render(79998007920000000000000, { mask: '#,##0' }, true)).toBe('79,998,007,920,000,000,000,000');
        expect(jSuites.mask.render(79998007920000000000000, { mask: '0.0000E+00' }, true)).toBe('7.9998e+22');
        expect(jSuites.mask.render(-79998007920000000000000, { mask: '0.0000E+00' }, true)).toBe('-7.9998e+22');
        expect(jSuites.mask.render(79998007920000000000000, { mask: '0.0000E+00' })).toBe('79998007920000000000000');
        expect(jSuites.mask.render(-79998007920000000000000, { mask: '0.0000E+00' })).toBe('-79998007920000000000000');

        expect(jSuites.mask.render(1234567890.123, { mask: '#,##0.00' })).toBe('1,234,567,890.123');
        expect(jSuites.mask.render(1234567890, { mask: '0.000000E+0' }, true)).toBe('1.234568e+9');
        expect(jSuites.mask.render(987654321.98765, { mask: '#,##0.0000' }, true)).toBe('987,654,321.9877');
        expect(jSuites.mask.render(12345678900, { mask: '0.00E+00' }, true)).toBe('1.23e+10');
        expect(jSuites.mask.render(98765432100000, { mask: '0.000000000E+00' }, true)).toBe('9.876543210e+13');
        //expect(jSuites.mask.render(1234567890.123456, { mask: '###,###.######' })).toBe('1,234,567,890.123456');
        //expect(jSuites.mask.render(123.456789, { mask: '0.0000####' })).toBe('123.456789');
        expect(jSuites.mask.render(123.4, { mask: '#,##0.0000' }, true)).toBe('123.4000');

        // expect(jSuites.mask.render(10000, { mask: '$#,##0;-$#,##0' })).toBe('$10,000');
        // expect(jSuites.mask.render(-10000, { mask: '$#,##0;-$#,##0' })).toBe('-$10,000');

        // For number value 0
        expect(jSuites.mask.render(0, { mask: '0' }, true)).toBe('0');
        expect(jSuites.mask.render(0, { mask: '0.00' }, true)).toBe('0.00');
        expect(jSuites.mask.render(0, { mask: '#,##0' }, true)).toBe('0');
        expect(jSuites.mask.render(0, { mask: '#,##0.00' }, true)).toBe('0.00');
        expect(jSuites.mask.render(0, { mask: '#,##0;-#,##0' }, true)).toBe('0');
        expect(jSuites.mask.render(0, { mask: '#,##0;[Red]-#,##0' }, true)).toBe('0');
        expect(jSuites.mask.render(0, { mask: '#,##0.00;-#,##0.00' }, true)).toBe('0.00');
        expect(jSuites.mask.render(0, { mask: 'XDR#,##0;-XDR#,##0' }, true)).toBe('XDR0');
        expect(jSuites.mask.render(0, { mask: 'XDR#,##0;[Red]-XDR#,##0' }, true)).toBe('XDR0');
        expect(jSuites.mask.render(0, { mask: 'XDR#,##0.00;-XDR#,##0.00' }, true)).toBe('XDR0.00');
        expect(jSuites.mask.render(0, { mask: 'XDR#,##0.00;[Red]-XDR#,##0.00' }, true)).toBe('XDR0.00');
        expect(jSuites.mask.render(0, { mask: '0%' }, true)).toBe('0%');
        expect(jSuites.mask.render(0, { mask: '0.00%' }, true)).toBe('0.00%');
        expect(jSuites.mask.render(0, { mask: '0.00E+00' }, true)).toBe('0.00e+00');
        expect(jSuites.mask.render(0, { mask: '##0.0E+0' }, true)).toBe('000.0e+0');
        expect(jSuites.mask.render(0, { mask: '# ?/?' }, true)).toBe('0    ');
        expect(jSuites.mask.render(0, { mask: '# ??/?' }, true)).toBe('0      ');
        expect(jSuites.mask.render(0, { mask: 'dd/mm/yyyy' }, true)).toBe('00/01/1900');
        expect(jSuites.mask.render(0, { mask: 'dd-mmm-yy' }, true)).toBe('00-Jan-00');
        expect(jSuites.mask.render(0, { mask: 'dd-mmm' }, true)).toBe('00-Jan');
        expect(jSuites.mask.render(0, { mask: 'mmm-yy' }, true)).toBe('Jan-00');
        expect(jSuites.mask.render(0, { mask: 'h:mm am/pm' }, true)).toBe('12:00 am');
        expect(jSuites.mask.render(0, { mask: 'h:mm:ss am/pm' }, true)).toBe('12:00:00 am');
        expect(jSuites.mask.render(0, { mask: 'h:mm' }, true)).toBe('0:00');
        expect(jSuites.mask.render(0, { mask: 'h:mm:ss' }, true)).toBe('0:00:00');
        expect(jSuites.mask.render(0, { mask: 'dd/mm/yyyy h:mm' }, true)).toBe('00/01/1900 0:00');
        expect(jSuites.mask.render(0, { mask: 'mm:ss' }, true)).toBe('00:00');
        expect(jSuites.mask.render(0, { mask: 'mm:ss.0' }, true)).toBe('00:00.0');
        expect(jSuites.mask.render(0, { mask: '@' }, true)).toBe('0');
        expect(jSuites.mask.render(0, { mask: '[h]:mm:ss' }, true)).toBe('0:00:00');
        expect(jSuites.mask.render(0, { mask: '*-XDR* #,##0*-;-XDR* #,##0_-;_-XDR* "-"_-;_-@_-' }, true)).toBe(' XDR                                    -');
        expect(jSuites.mask.render(0, { mask: '*-* #,##0*-;-* #,##0_-;_-* "-"_-;_-@_-' }, true)).toBe('                                              -');
        expect(jSuites.mask.render(0, { mask: '*-XDR* #,##0.00*-;-XDR* #,##0.00_-;_-XDR* "-"??_-;_-@_-' }, true)).toBe(' XDR                                  -  ');
        expect(jSuites.mask.render(0, { mask: '*-* #,##0.00*-;-* #,##0.00_-;_-* "-"??_-;_-@_-' }, true)).toBe('                                            -  ');
        expect(jSuites.mask.render(0, { mask: '[$-en-US]h:mm:ss AM/PM' }, true)).toBe('12:00:00 AM');
        expect(jSuites.mask.render(0, { mask: '[$-en-001]dddd, d mmmm yyyy' }, true)).toBe('0');
        expect(jSuites.mask.render(0, { mask: '[$-en-US]h:mm:ss am/pm' }, true)).toBe('12:00:00 AM');

        // For number value 1
        expect(jSuites.mask.render(1, { mask: '0' }, true)).toBe('1');
        expect(jSuites.mask.render(1, { mask: '0.00' }, true)).toBe('1.00');
        expect(jSuites.mask.render(1, { mask: '#,##0' }, true)).toBe('1');
        expect(jSuites.mask.render(1, { mask: '#,##0.00' }, true)).toBe('1.00');
        expect(jSuites.mask.render(1, { mask: '#,##0;-#,##0' }, true)).toBe('1');
        expect(jSuites.mask.render(1, { mask: '#,##0;[Red]-#,##0' }, true)).toBe('1');
        expect(jSuites.mask.render(1, { mask: '#,##0.00;-#,##0.00' }, true)).toBe('1.00');
        expect(jSuites.mask.render(1, { mask: 'XDR#,##0;-XDR#,##0' }, true)).toBe('XDR1');
        expect(jSuites.mask.render(1, { mask: 'XDR#,##0;[Red]-XDR#,##0' }, true)).toBe('XDR1');
        expect(jSuites.mask.render(1, { mask: 'XDR#,##0.00;-XDR#,##0.00' }, true)).toBe('XDR1.00');
        expect(jSuites.mask.render(1, { mask: 'XDR#,##0.00;[Red]-XDR#,##0.00' }, true)).toBe('XDR1.00');
        expect(jSuites.mask.render(1, { mask: '0%' }, true)).toBe('100%');
        expect(jSuites.mask.render(1, { mask: '0.00%' }, true)).toBe('100.00%');
        expect(jSuites.mask.render(1, { mask: '0.00E+00' }, true)).toBe('1.00e+00');
        expect(jSuites.mask.render(1, { mask: '##0.0E+0' }, true)).toBe('1.0e+0');
        expect(jSuites.mask.render(1, { mask: '# ?/?' }, true)).toBe('1   ');
        expect(jSuites.mask.render(1, { mask: '# ??/??' }, true)).toBe('1     ');
        expect(jSuites.mask.render(1, { mask: 'dd/mm/yyyy' }, true)).toBe('01/01/1900');
        expect(jSuites.mask.render(1, { mask: 'dd-mmm-yy' }, true)).toBe('01-Jan-00');
        expect(jSuites.mask.render(1, { mask: 'dd-mmm' }, true)).toBe('01-Jan');
        expect(jSuites.mask.render(1, { mask: 'mmm-yy' }, true)).toBe('Jan-00');
        expect(jSuites.mask.render(1, { mask: 'h:mm am/pm' }, true)).toBe('12:00 am');
        expect(jSuites.mask.render(1, { mask: 'h:mm:ss am/pm' }, true)).toBe('12:00:00 am');
        expect(jSuites.mask.render(1, { mask: 'h:mm' }, true)).toBe('0:00');
        expect(jSuites.mask.render(1, { mask: 'h:mm:ss' }, true)).toBe('0:00:00');
        expect(jSuites.mask.render(1, { mask: 'dd/mm/yyyy h:mm' }, true)).toBe('01/01/1900 0:00');
        expect(jSuites.mask.render(1, { mask: 'mm:ss' }, true)).toBe('00:00');
        expect(jSuites.mask.render(1, { mask: 'mm:ss.0' }, true)).toBe('00:00.0');
        expect(jSuites.mask.render(1, { mask: '@' }, true)).toBe('1');
        expect(jSuites.mask.render(1, { mask: '[h]:mm:ss' }, true)).toBe('24:00:00');
        expect(jSuites.mask.render(1, { mask: '*-XDR* #,##0*-;-XDR* #,##0_-;_-XDR* "-"_-;_-@_-' }, true)).toBe(' XDR                                    1');
        expect(jSuites.mask.render(1, { mask: '*-* #,##0*-;-* #,##0_-;_-* "-"_-;_-@_-' }, true)).toBe('                                             1');
        expect(jSuites.mask.render(1, { mask: '*-XDR* #,##0.00*-;-XDR* #,##0.00_-;_-XDR* "-"??_-;_-@_-' }, true)).toBe(' XDR                              1.00');
        expect(jSuites.mask.render(1, { mask: '*-* #,##0.00*-;-* #,##0.00_-;_-* "-"??_-;_-@_-' }, true)).toBe('                                        1.00');
        expect(jSuites.mask.render(1, { mask: '[$-en-US]h:mm:ss AM/PM' }, true)).toBe('12:00:00 AM');
        expect(jSuites.mask.render(1, { mask: '[$-en-001]dddd, d mmmm yyyy' }, true)).toBe('Sunday, 1 January 1900');
        expect(jSuites.mask.render(1, { mask: '[$-en-US]h:mm:ss am/pm' }, true)).toBe('12:00:00 AM');

        // For number value -1
        expect(jSuites.mask.render(-1, { mask: '0' }, true)).toBe('-1');
        expect(jSuites.mask.render(-1, { mask: '0.00' }, true)).toBe('-1.00');
        expect(jSuites.mask.render(-1, { mask: '#,##0' }, true)).toBe('-1');
        expect(jSuites.mask.render(-1, { mask: '#,##0.00' }, true)).toBe('-1.00');
        expect(jSuites.mask.render(-1, { mask: '#,##0;-#,##0' }, true)).toBe('-1');
        expect(jSuites.mask.render(-1, { mask: '#,##0;[Red]-#,##0' }, true)).toBe('-1');
        expect(jSuites.mask.render(-1, { mask: '#,##0.00;-#,##0.00' }, true)).toBe('-1.00');
        expect(jSuites.mask.render(-1, { mask: 'XDR#,##0;-XDR#,##0' }, true)).toBe('-XDR1');
        expect(jSuites.mask.render(-1, { mask: 'XDR#,##0;[Red]-XDR#,##0' }, true)).toBe('-XDR1');
        expect(jSuites.mask.render(-1, { mask: 'XDR#,##0.00;-XDR#,##0.00' }, true)).toBe('-XDR1.00');
        expect(jSuites.mask.render(-1, { mask: 'XDR#,##0.00;[Red]-XDR#,##0.00' }, true)).toBe('-XDR1.00');
        expect(jSuites.mask.render(-1, { mask: '0%' }, true)).toBe('-100%');
        expect(jSuites.mask.render(-1, { mask: '0.00%' }, true)).toBe('-100.00%');
        expect(jSuites.mask.render(-1, { mask: '0.00E+00' }, true)).toBe('-1.00e+00');
        expect(jSuites.mask.render(-1, { mask: '##0.0E+0' }, true)).toBe('-1.0e+0');
        expect(jSuites.mask.render(-1, { mask: '# ?/?' }, true)).toBe('-1    ');
        expect(jSuites.mask.render(-1, { mask: '# ??/??' }, true)).toBe('-1      ');
        expect(jSuites.mask.render(-1, { mask: 'dd/mm/yyyy' }, true)).toBe('-1');
        expect(jSuites.mask.render(-1, { mask: 'dd-mmm-yy' }, true)).toBe('-1');
        expect(jSuites.mask.render(-1, { mask: 'dd-mmm' }, true)).toBe('-1');
        expect(jSuites.mask.render(-1, { mask: 'mmm-yy' }, true)).toBe('-1');
        expect(jSuites.mask.render(-1, { mask: 'h:mm am/pm' }, true)).toBe('-1');
        expect(jSuites.mask.render(-1, { mask: 'h:mm:ss am/pm' }, true)).toBe('-1');
        expect(jSuites.mask.render(-1, { mask: 'h:mm' }, true)).toBe('-1');
        expect(jSuites.mask.render(-1, { mask: 'h:mm:ss' }, true)).toBe('-1');
        expect(jSuites.mask.render(-1, { mask: 'dd/mm/yyyy h:mm' }, true)).toBe('-1');
        expect(jSuites.mask.render(-1, { mask: 'mm:ss' }, true)).toBe('-1');
        expect(jSuites.mask.render(-1, { mask: 'mm:ss.0' }, true)).toBe('-1');
        expect(jSuites.mask.render(-1, { mask: '@' }, true)).toBe('-1');
        expect(jSuites.mask.render(-1, { mask: '[h]:mm:ss' }, true)).toBe('-1');
        expect(jSuites.mask.render(-1, { mask: '_-XDR* #,##0_-;-XDR* #,##0_-;_-XDR* "-"_-;_-@_-' }, true)).toBe('-XDR1 ');
        expect(jSuites.mask.render(-1, { mask: '_-* #,##0_-;-* #,##0_-;_-* "-"_-;_-@_-' }, true)).toBe('-1 ');
        expect(jSuites.mask.render(-1, { mask: '_-XDR* #,##0.00_-;-XDR* #,##0.00_-;_-XDR* "-"??_-;_-@_-' }, true)).toBe('-XDR1.00 ');
        expect(jSuites.mask.render(-1, { mask: '_-* #,##0.00_-;-* #,##0.00_-;_-* "-"??_-;_-@_-' }, true)).toBe('-1.00 ');
        expect(jSuites.mask.render(-1, { mask: '[$-en-US]h:mm:ss AM/PM' }, true)).toBe('-1');
        expect(jSuites.mask.render(-1, { mask: '[$-en-001]dddd, d mmmm yyyy' }, true)).toBe('-1');
        expect(jSuites.mask.render(-1, { mask: '[$-en-US]h:mm:ss am/pm' }, true)).toBe('-1');

        // For decimal number 0.5
        expect(jSuites.mask.render(0.5, { mask: '0' }, true)).toBe('1');
        expect(jSuites.mask.render(0.5, { mask: '0.00' }, true)).toBe('0.50');
        expect(jSuites.mask.render(0.5, { mask: '#,##0' }, true)).toBe('1');
        expect(jSuites.mask.render(0.5, { mask: '#,##0.00' }, true)).toBe('0.50');
        expect(jSuites.mask.render(0.5, { mask: '#,##0;-#,##0' }, true)).toBe('1');
        expect(jSuites.mask.render(0.5, { mask: '#,##0;[Red]-#,##0' }, true)).toBe('1');
        expect(jSuites.mask.render(0.5, { mask: '#,##0.00;-#,##0.00' }, true)).toBe('0.50');
        expect(jSuites.mask.render(0.5, { mask: 'XDR#,##0;-XDR#,##0' }, true)).toBe('XDR1');
        expect(jSuites.mask.render(0.5, { mask: 'XDR#,##0;[Red]-XDR#,##0' }, true)).toBe('XDR1');
        expect(jSuites.mask.render(0.5, { mask: 'XDR#,##0.00;-XDR#,##0.00' }, true)).toBe('XDR0.50');
        expect(jSuites.mask.render(0.5, { mask: 'XDR#,##0.00;[Red]-XDR#,##0.00' }, true)).toBe('XDR0.50');
        expect(jSuites.mask.render(0.5, { mask: '0%' }, true)).toBe('50%');
        expect(jSuites.mask.render(0.5, { mask: '0.00%' }, true)).toBe('50.00%');
        expect(jSuites.mask.render(0.5, { mask: '0.00E+00' }, true)).toBe('5.00e-01');
        expect(jSuites.mask.render(0.5, { mask: '##0.0E+0' }, true)).toBe('500.0e-3');
        expect(jSuites.mask.render(0.5, { mask: '# ?/?' }, true)).toBe(' 1/2');
        expect(jSuites.mask.render(0.5, { mask: '# ??/??' }, true)).toBe('  1/2');
        expect(jSuites.mask.render(0.5, { mask: 'dd/mm/yyyy' }, true)).toBe('00/01/1900');
        expect(jSuites.mask.render(0.5, { mask: 'dd-mmm-yy' }, true)).toBe('00-Jan-00');
        expect(jSuites.mask.render(0.5, { mask: 'dd-mmm' }, true)).toBe('00-Jan');
        expect(jSuites.mask.render(0.5, { mask: 'mmm-yy' }, true)).toBe('Jan-00');
        expect(jSuites.mask.render(0.5, { mask: 'h:mm am/pm' }, true)).toBe('12:00 pm');
        expect(jSuites.mask.render(0.5, { mask: 'h:mm:ss am/pm' }, true)).toBe('12:00:00 pm');
        expect(jSuites.mask.render(0.5, { mask: 'h:mm' }, true)).toBe('12:00');
        expect(jSuites.mask.render(0.5, { mask: 'h:mm:ss' }, true)).toBe('12:00:00');
        expect(jSuites.mask.render(0.5, { mask: 'dd/mm/yyyy h:mm' }, true)).toBe('00/01/1900 12:00');
        expect(jSuites.mask.render(0.5, { mask: 'mm:ss' }, true)).toBe('00:00');
        expect(jSuites.mask.render(0.5, { mask: 'mm:ss.0' }, true)).toBe('00:00.0');
        expect(jSuites.mask.render(0.5, { mask: '@' }, true)).toBe('0.5');
        expect(jSuites.mask.render(0.5, { mask: '[h]:mm:ss' }, true)).toBe('12:00:00');
        expect(jSuites.mask.render(0.5, { mask: '*-XDR* #,##0*-;-XDR* #,##0*-;*-XDR* "-"*-;*-@*-' }, true)).toBe(' XDR                                    1');
        expect(jSuites.mask.render(0.5, { mask: '- #,##0-;- #,##0*-;*-* "-"*-;*-@*-' }, true)).toBe('                                             1');
        expect(jSuites.mask.render(0.5, { mask: '*-XDR* #,##0.00*-;-XDR* #,##0.00*-;*-XDR* "-"??*-;*-@*-' }, true)).toBe(' XDR                              0.50');
        expect(jSuites.mask.render(0.5, { mask: '- #,##0.00-;- #,##0.00*-;*-* "-"??*-;*-@*-' }, true)).toBe('                                        0.50');
        expect(jSuites.mask.render(0.5, { mask: '[$-en-US]h:mm:ss AM/PM' }, true)).toBe('12:00:00 PM');
        expect(jSuites.mask.render(0.5, { mask: '[$-en-001]dddd, d mmmm yyyy' }, true)).toBe('0.5');
        expect(jSuites.mask.render(0.5, { mask: '[$-en-US]h:mm:ss am/pm' }, true)).toBe('12:00:00 PM');
    });

    // For decimal number 0.1234
    expect(jSuites.mask.render(0.1234, { mask: '0' }, true)).toBe('0');
    expect(jSuites.mask.render(0.1234, { mask: '0.00' }, true)).toBe('0.12');
    expect(jSuites.mask.render(0.1234, { mask: '#,##0' }, true)).toBe('0');
    expect(jSuites.mask.render(0.1234, { mask: '#,##0.00' }, true)).toBe('0.12');
    expect(jSuites.mask.render(0.1234, { mask: '#,##0;-#,##0' }, true)).toBe('0');
    expect(jSuites.mask.render(0.1234, { mask: '#,##0;[Red]-#,##0' }, true)).toBe('0');
    expect(jSuites.mask.render(0.1234, { mask: '#,##0.00;-#,##0.00' }, true)).toBe('0.12');
    expect(jSuites.mask.render(0.1234, { mask: 'XDR#,##0;-XDR#,##0' }, true)).toBe('XDR0');
    expect(jSuites.mask.render(0.1234, { mask: 'XDR#,##0;[Red]-XDR#,##0' }, true)).toBe('XDR0');
    expect(jSuites.mask.render(0.1234, { mask: 'XDR#,##0.00;-XDR#,##0.00' }, true)).toBe('XDR0.12');
    expect(jSuites.mask.render(0.1234, { mask: 'XDR#,##0.00;[Red]-XDR#,##0.00' }, true)).toBe('XDR0.12');
    expect(jSuites.mask.render(0.1234, { mask: '0%' }, true)).toBe('12%');
    expect(jSuites.mask.render(0.1234, { mask: '0.00%' }, true)).toBe('12.34%');
    expect(jSuites.mask.render(0.1234, { mask: '0.00E+00' }, true)).toBe('1.23e-01');
    expect(jSuites.mask.render(0.1234, { mask: '##0.0E+0' }, true)).toBe('123.4e-3');
    expect(jSuites.mask.render(0.1234, { mask: '# ?/?' }, true)).toBe(' 1/8');
    expect(jSuites.mask.render(0.1234, { mask: '# ??/??' }, true)).toBe(' 10/81');
    expect(jSuites.mask.render(0.1234, { mask: 'dd/mm/yyyy' }, true)).toBe('00/01/1900');
    expect(jSuites.mask.render(0.1234, { mask: 'dd-mmm-yy' }, true)).toBe('00-Jan-00');
    expect(jSuites.mask.render(0.1234, { mask: 'dd-mmm' }, true)).toBe('00-Jan');
    expect(jSuites.mask.render(0.1234, { mask: 'mmm-yy' }, true)).toBe('Jan-00');
    expect(jSuites.mask.render(0.1234, { mask: 'h:mm am/pm' }, true)).toBe('2:57 am');
    expect(jSuites.mask.render(0.1234, { mask: 'h:mm:ss am/pm' }, true)).toBe('2:57:42 am');
    expect(jSuites.mask.render(0.1234, { mask: 'h:mm' }, true)).toBe('2:57');
    expect(jSuites.mask.render(0.1234, { mask: 'h:mm:ss' }, true)).toBe('2:57:42');
    expect(jSuites.mask.render(0.1234, { mask: 'dd/mm/yyyy h:mm' }, true)).toBe('00/01/1900 2:57');
    expect(jSuites.mask.render(0.1234, { mask: 'mm:ss' }, true)).toBe('57:42');
    expect(jSuites.mask.render(0.1234, { mask: 'mm:ss.0' }, true)).toBe('57:41.8');
    expect(jSuites.mask.render(0.1234, { mask: '@' }, true)).toBe('0.1234');
    expect(jSuites.mask.render(0.1234, { mask: '[h]:mm:ss' }, true)).toBe('2:57:42');
    expect(jSuites.mask.render(0.1234, { mask: '*-XDR* #,##0*-;-XDR* #,##0_-;_-XDR* "-"_-;_-@_-' }, true)).toBe(' XDR                                    0');
    expect(jSuites.mask.render(0.1234, { mask: '*-* #,##0*-;-* #,##0_-;_-* "-"_-;_-@_-' }, true)).toBe('                                             0');
    expect(jSuites.mask.render(0.1234, { mask: '*-XDR* #,##0.00*-;-XDR* #,##0.00_-;_-XDR* "-"??_-;_-@_-' }, true)).toBe(' XDR                              0.12');
    expect(jSuites.mask.render(0.1234, { mask: '*-* #,##0.00*-;-* #,##0.00_-;_-* "-"??_-;_-@_-' }, true)).toBe('                                        0.12');
    expect(jSuites.mask.render(0.1234, { mask: '[$-en-US]h:mm:ss AM/PM' }, true)).toBe('2:57:42 AM');
    expect(jSuites.mask.render(0.1234, { mask: '[$-en-001]dddd, d mmmm yyyy' }, true)).toBe('0.1234');
    expect(jSuites.mask.render(0.1234, { mask: '[$-en-US]h:mm:ss am/pm' }, true)).toBe('2:57:42 AM');

    // For decimal number 1234.56
    expect(jSuites.mask.render(1234.56, { mask: '0' }, true)).toBe('1235');
    expect(jSuites.mask.render(1234.56, { mask: '0.00' }, true)).toBe('1234.56');
    expect(jSuites.mask.render(1234.56, { mask: '#,##0' }, true)).toBe('1,235');
    expect(jSuites.mask.render(1234.56, { mask: '#,##0.00' }, true)).toBe('1,234.56');
    expect(jSuites.mask.render(1234.56, { mask: '#,##0;-#,##0' }, true)).toBe('1,235');
    expect(jSuites.mask.render(1234.56, { mask: '#,##0;[Red]-#,##0' }, true)).toBe('1,235');
    expect(jSuites.mask.render(1234.56, { mask: '#,##0.00;-#,##0.00' }, true)).toBe('1,234.56');
    expect(jSuites.mask.render(1234.56, { mask: 'XDR#,##0;-XDR#,##0' }, true)).toBe('XDR1,235');
    expect(jSuites.mask.render(1234.56, { mask: 'XDR#,##0;[Red]-XDR#,##0' }, true)).toBe('XDR1,235');
    expect(jSuites.mask.render(1234.56, { mask: 'XDR#,##0.00;-XDR#,##0.00' }, true)).toBe('XDR1,234.56');
    expect(jSuites.mask.render(1234.56, { mask: 'XDR#,##0.00;[Red]-XDR#,##0.00' }, true)).toBe('XDR1,234.56');
    expect(jSuites.mask.render(1234.56, { mask: '0%' }, true)).toBe('123456%');
    expect(jSuites.mask.render(1234.56, { mask: '0.00%' }, true)).toBe('123456.00%');
    expect(jSuites.mask.render(1234.56, { mask: '0.00E+00' }, true)).toBe('1.23e+03');
    expect(jSuites.mask.render(1234.56, { mask: '##0.0E+0' }, true)).toBe('1.2e+3');
    expect(jSuites.mask.render(1234.56, { mask: '# ?/?' }, true)).toBe('1234 5/9');
    expect(jSuites.mask.render(1234.56, { mask: '# ??/??' }, true)).toBe('1234 14/25');
    expect(jSuites.mask.render(1234.56, { mask: 'dd/mm/yyyy' }, true)).toBe('18/05/1903');
    expect(jSuites.mask.render(1234.56, { mask: 'dd-mmm-yy' }, true)).toBe('18-May-03');
    expect(jSuites.mask.render(1234.56, { mask: 'dd-mmm' }, true)).toBe('18-May');
    expect(jSuites.mask.render(1234.56, { mask: 'mmm-yy' }, true)).toBe('May-03');
    expect(jSuites.mask.render(1234.56, { mask: 'h:mm am/pm' }, true)).toBe('1:26 pm');
    expect(jSuites.mask.render(1234.56, { mask: 'h:mm:ss am/pm' }, true)).toBe('1:26:24 pm');
    expect(jSuites.mask.render(1234.56, { mask: 'h:mm' }, true)).toBe('13:26');
    expect(jSuites.mask.render(1234.56, { mask: 'h:mm:ss' }, true)).toBe('13:26:24');
    expect(jSuites.mask.render(1234.56, { mask: 'dd/mm/yyyy h:mm' }, true)).toBe('18/05/1903 13:26');
    expect(jSuites.mask.render(1234.56, { mask: 'mm:ss' }, true)).toBe('26:24');
    expect(jSuites.mask.render(1234.56, { mask: 'mm:ss.0' }, true)).toBe('26:24.0');
    expect(jSuites.mask.render(1234.56, { mask: '@' }, true)).toBe('1234.56');
    expect(jSuites.mask.render(1234.56, { mask: '[h]:mm:ss' }, true)).toBe('29629:26:24');
    expect(jSuites.mask.render(1234.56, { mask: '*-XDR* #,##0*-;-XDR* #,##0_-;_-XDR* "-"_-;_-@_-' }, true)).toBe(' XDR                           1,235');
    expect(jSuites.mask.render(1234.56, { mask: '*-* #,##0*-;-* #,##0_-;_-* "-"_-;_-@_-' }, true)).toBe('                                     1,235');
    expect(jSuites.mask.render(1234.56, { mask: '*-XDR* #,##0.00*-;-XDR* #,##0.00_-;_-XDR* "-"??_-;_-@_-' }, true)).toBe(' XDR                     1,234.56');
    expect(jSuites.mask.render(1234.56, { mask: '*-* #,##0.00*-;-* #,##0.00_-;_-* "-"??_-;_-@_-' }, true)).toBe('                               1,234.56');
    expect(jSuites.mask.render(1234.56, { mask: '[$-en-US]h:mm:ss AM/PM' }, true)).toBe('1:26:24 PM');
    expect(jSuites.mask.render(1234.56, { mask: '[$-en-001]dddd, d mmmm yyyy' }, true)).toBe('Monday, 18 May 1903');
    expect(jSuites.mask.render(1234.56, { mask: '[$-en-US]h:mm:ss am/pm' }, true)).toBe('1:26:24 PM');

    // For text "Hello World"
    expect(jSuites.mask.render('Hello World', { mask: '0' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: '0.00' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: '#,##0' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: '#,##0.00' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: '#,##0;-#,##0' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: '#,##0;[Red]-#,##0' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: '#,##0.00;-#,##0.00' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: 'XDR#,##0;-XDR#,##0' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: 'XDR#,##0;[Red]-XDR#,##0' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: 'XDR#,##0.00;-XDR#,##0.00' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: 'XDR#,##0.00;[Red]-XDR#,##0.00' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: '0%' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: '0.00%' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: '0.00E+00' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: '##0.0E+0' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: '# ?/?' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: '# ??/??' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: 'dd/mm/yyyy' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: 'dd-mmm-yy' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: 'dd-mmm' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: 'mmm-yy' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: 'h:mm am/pm' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: 'h:mm:ss am/pm' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: 'h:mm' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: 'h:mm:ss' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: 'dd/mm/yyyy h:mm' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: 'mm:ss' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: 'mm:ss.0' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: '@' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: '[h]:mm:ss' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: '*-XDR* #,##0*-;-XDR* #,##0_-;_-XDR* "-"_-;_-@_-' }, true)).toBe(' Hello World ');
    expect(jSuites.mask.render('Hello World', { mask: '*-* #,##0*-;-* #,##0_-;_-* "-"_-;_-@_-' }, true)).toBe(' Hello World ');
    expect(jSuites.mask.render('Hello World', { mask: '*-XDR* #,##0.00*-;-XDR* #,##0.00_-;_-XDR* "-"??_-;_-@_-' }, true)).toBe(' Hello World ');
    expect(jSuites.mask.render('Hello World', { mask: '*-* #,##0.00*-;-* #,##0.00_-;_-* "-"??_-;_-@_-' }, true)).toBe(' Hello World ');
    expect(jSuites.mask.render('Hello World', { mask: '[$-en-US]h:mm:ss AM/PM' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: '[$-en-001]dddd, d mmmm yyyy' }, true)).toBe('Hello World');
    expect(jSuites.mask.render('Hello World', { mask: '[$-en-US]h:mm:ss am/pm' }, true)).toBe('Hello World');

    // For date value "20/09/1999"
    expect(jSuites.mask.render('20/09/1999', { mask: '0' }, true)).toBe('36423');
    expect(jSuites.mask.render('20/09/1999', { mask: '0.00' }, true)).toBe('36423.00');
    expect(jSuites.mask.render('20/09/1999', { mask: '#,##0' }, true)).toBe('36,423');
    expect(jSuites.mask.render('20/09/1999', { mask: '#,##0.00' }, true)).toBe('36,423.00');
    expect(jSuites.mask.render('20/09/1999', { mask: '#,##0;-#,##0' }, true)).toBe('36,423');
    expect(jSuites.mask.render('20/09/1999', { mask: '#,##0;[Red]-#,##0' }, true)).toBe('36,423');
    expect(jSuites.mask.render('20/09/1999', { mask: '#,##0.00;-#,##0.00' }, true)).toBe('36,423.00');
    expect(jSuites.mask.render('20/09/1999', { mask: 'XDR#,##0;-XDR#,##0' }, true)).toBe('XDR36,423');
    expect(jSuites.mask.render('20/09/1999', { mask: 'XDR#,##0;[Red]-XDR#,##0' }, true)).toBe('XDR36,423');
    expect(jSuites.mask.render('20/09/1999', { mask: 'XDR#,##0.00;-XDR#,##0.00' }, true)).toBe('XDR36,423.00');
    expect(jSuites.mask.render('20/09/1999', { mask: 'XDR#,##0.00;[Red]-XDR#,##0.00' }, true)).toBe('XDR36,423.00');
    expect(jSuites.mask.render('20/09/1999', { mask: '0%' }, true)).toBe('3642300%');
    expect(jSuites.mask.render('20/09/1999', { mask: '0.00%' }, true)).toBe('3642300.00%');
    expect(jSuites.mask.render('20/09/1999', { mask: '0.00E+00' }, true)).toBe('3.64e+04');
    expect(jSuites.mask.render('20/09/1999', { mask: '##0.0E+0' }, true)).toBe('36.4e+3');
    expect(jSuites.mask.render('20/09/1999', { mask: '# ?/?' }, true)).toBe('36423    ');
    expect(jSuites.mask.render('20/09/1999', { mask: '# ??/??' }, true)).toBe('36423      ');
    expect(jSuites.mask.render('20/09/1999', { mask: 'dd/mm/yyyy' }, true)).toBe('20/09/1999');
    expect(jSuites.mask.render('20/09/1999', { mask: 'dd-mmm-yy' }, true)).toBe('20-Sept-99');
    expect(jSuites.mask.render('20/09/1999', { mask: 'dd-mmm' }, true)).toBe('20-Sept');
    expect(jSuites.mask.render('20/09/1999', { mask: 'mmm-yy' }, true)).toBe('Sept-99');
    expect(jSuites.mask.render('20/09/1999', { mask: 'h:mm am/pm' }, true)).toBe('12:00 am');
    expect(jSuites.mask.render('20/09/1999', { mask: 'h:mm:ss am/pm' }, true)).toBe('12:00:00 am');
    expect(jSuites.mask.render('20/09/1999', { mask: 'h:mm' }, true)).toBe('0:00');
    expect(jSuites.mask.render('20/09/1999', { mask: 'h:mm:ss' }, true)).toBe('0:00:00');
    expect(jSuites.mask.render('20/09/1999', { mask: 'dd/mm/yyyy h:mm' }, true)).toBe('20/09/1999 0:00');
    expect(jSuites.mask.render('20/09/1999', { mask: 'mm:ss' }, true)).toBe('00:00');
    expect(jSuites.mask.render('20/09/1999', { mask: 'mm:ss.0' }, true)).toBe('00:00.0');
    expect(jSuites.mask.render('20/09/1999', { mask: '@' }, true)).toBe('36423');
    expect(jSuites.mask.render('20/09/1999', { mask: '[h]:mm:ss' }, true)).toBe('874152:00:00');
    expect(jSuites.mask.render('20/09/1999', { mask: '*-XDR* #,##0*-;-XDR* #,##0_-;_-XDR* "-"_-;_-@_-' }, true)).toBe(' XDR                         36,423');
    expect(jSuites.mask.render('20/09/1999', { mask: '*-* #,##0*-;-* #,##0_-;_-* "-"_-;_-@_-' }, true)).toBe('                                  36,423');
    expect(jSuites.mask.render('20/09/1999', { mask: '*-XDR* #,##0.00*-;-XDR* #,##0.00_-;_-XDR* "-"??_-;_-@_-' }, true)).toBe(' XDR                   36,423.00');
    expect(jSuites.mask.render('20/09/1999', { mask: '*-* #,##0.00*-;-* #,##0.00_-;_-* "-"??_-;_-@_-' }, true)).toBe('                             36,423.00');
    expect(jSuites.mask.render('20/09/1999', { mask: '[$-en-US]h:mm:ss AM/PM' }, true)).toBe('12:00:00 AM');
    expect(jSuites.mask.render('20/09/1999', { mask: '[$-en-001]dddd, d mmmm yyyy' }, true)).toBe('20/09/1999');
    expect(jSuites.mask.render('20/09/1999', { mask: '[$-en-US]h:mm:ss am/pm' }, true)).toBe('12:00:00 AM');

    // For date value "01/01/2000"
    expect(jSuites.mask.render('01/01/2000', { mask: '0' }, true)).toBe('36526');
    expect(jSuites.mask.render('01/01/2000', { mask: '0.00' }, true)).toBe('36526.00');
    expect(jSuites.mask.render('01/01/2000', { mask: '#,##0' }, true)).toBe('36,526');
    expect(jSuites.mask.render('01/01/2000', { mask: '#,##0.00' }, true)).toBe('36,526.00');
    expect(jSuites.mask.render('01/01/2000', { mask: '#,##0;-#,##0' }, true)).toBe('36,526');
    expect(jSuites.mask.render('01/01/2000', { mask: '#,##0;[Red]-#,##0' }, true)).toBe('36,526');
    expect(jSuites.mask.render('01/01/2000', { mask: '#,##0.00;-#,##0.00' }, true)).toBe('36,526.00');
    expect(jSuites.mask.render('01/01/2000', { mask: 'XDR#,##0;-XDR#,##0' }, true)).toBe('XDR36,526');
    expect(jSuites.mask.render('01/01/2000', { mask: 'XDR#,##0;[Red]-XDR#,##0' }, true)).toBe('XDR36,526');
    expect(jSuites.mask.render('01/01/2000', { mask: 'XDR#,##0.00;-XDR#,##0.00' }, true)).toBe('XDR36,526.00');
    expect(jSuites.mask.render('01/01/2000', { mask: 'XDR#,##0.00;[Red]-XDR#,##0.00' }, true)).toBe('XDR36,526.00');
    expect(jSuites.mask.render('01/01/2000', { mask: '0%' }, true)).toBe('3652600%');
    expect(jSuites.mask.render('01/01/2000', { mask: '0.00%' }, true)).toBe('3652600.00%');
    expect(jSuites.mask.render('01/01/2000', { mask: '0.00E+00' }, true)).toBe('3.65e+04');
    expect(jSuites.mask.render('01/01/2000', { mask: '##0.0E+0' }, true)).toBe('36.5e+3');
    expect(jSuites.mask.render('01/01/2000', { mask: '# ?/?' }, true)).toBe('36526    ');
    expect(jSuites.mask.render('01/01/2000', { mask: '# ??/??' }, true)).toBe('36526      ');
    expect(jSuites.mask.render('01/01/2000', { mask: 'dd/mm/yyyy' }, true)).toBe('01/01/2000');
    expect(jSuites.mask.render('01/01/2000', { mask: 'dd-mmm-yy' }, true)).toBe('01-Jan-00');
    expect(jSuites.mask.render('01/01/2000', { mask: 'dd-mmm' }, true)).toBe('01-Jan');
    expect(jSuites.mask.render('01/01/2000', { mask: 'mmm-yy' }, true)).toBe('Jan-00');
    expect(jSuites.mask.render('01/01/2000', { mask: 'h:mm am/pm' }, true)).toBe('12:00 am');
    expect(jSuites.mask.render('01/01/2000', { mask: 'h:mm:ss am/pm' }, true)).toBe('12:00:00 am');
    expect(jSuites.mask.render('01/01/2000', { mask: 'h:mm' }, true)).toBe('0:00');
    expect(jSuites.mask.render('01/01/2000', { mask: 'h:mm:ss' }, true)).toBe('0:00:00');
    expect(jSuites.mask.render('01/01/2000', { mask: 'dd/mm/yyyy h:mm' }, true)).toBe('01/01/2000 0:00');
    expect(jSuites.mask.render('01/01/2000', { mask: 'mm:ss' }, true)).toBe('00:00');
    expect(jSuites.mask.render('01/01/2000', { mask: 'mm:ss.0' }, true)).toBe('00:00.0');
    expect(jSuites.mask.render('01/01/2000', { mask: '@' }, true)).toBe('36526');
    expect(jSuites.mask.render('01/01/2000', { mask: '[h]:mm:ss' }, true)).toBe('876624:00:00');
    expect(jSuites.mask.render('01/01/2000', { mask: '*-XDR* #,##0*-;-XDR* #,##0_-;_-XDR* "-"_-;_-@_-' }, true)).toBe(' XDR                         36,526');
    expect(jSuites.mask.render('01/01/2000', { mask: '*-* #,##0*-;-* #,##0_-;_-* "-"_-;_-@_-' }, true)).toBe('                                  36,526');
    expect(jSuites.mask.render('01/01/2000', { mask: '*-XDR* #,##0.00*-;-XDR* #,##0.00_-;_-XDR* "-"??_-;_-@_-' }, true)).toBe(' XDR                   36,526.00');
    expect(jSuites.mask.render('01/01/2000', { mask: '*-* #,##0.00*-;-* #,##0.00_-;_-* "-"??_-;_-@_-' }, true)).toBe('                             36,526.00');
    expect(jSuites.mask.render('01/01/2000', { mask: '[$-en-US]h:mm:ss AM/PM' }, true)).toBe('12:00:00 AM');
    expect(jSuites.mask.render('01/01/2000', { mask: '[$-en-001]dddd, d mmmm yyyy' }, true)).toBe('01/01/2000');
    expect(jSuites.mask.render('01/01/2000', { mask: '[$-en-US]h:mm:ss am/pm' }, true)).toBe('12:00:00 AM');

    // For empty cell
    // Additional test cases for null value
    expect(jSuites.mask.render(undefined, { mask: '0' }, true)).toBe('0');
    expect(jSuites.mask.render(undefined, { mask: '0.00' }, true)).toBe('0.00');
    expect(jSuites.mask.render(undefined, { mask: '#,##0' }, true)).toBe('0');
    expect(jSuites.mask.render(undefined, { mask: '#,##0.00' }, true)).toBe('0.00');
    expect(jSuites.mask.render(undefined, { mask: '#,##0;-#,##0' }, true)).toBe('0');
    expect(jSuites.mask.render(undefined, { mask: '#,##0;[Red]-#,##0' }, true)).toBe('0');
    expect(jSuites.mask.render(undefined, { mask: '#,##0.00;-#,##0.00' }, true)).toBe('0.00');
    expect(jSuites.mask.render(undefined, { mask: 'XDR#,##0;-XDR#,##0' }, true)).toBe('XDR0');
    expect(jSuites.mask.render(undefined, { mask: 'XDR#,##0;[Red]-XDR#,##0' }, true)).toBe('XDR0');
    expect(jSuites.mask.render(undefined, { mask: 'XDR#,##0.00;-XDR#,##0.00' }, true)).toBe('XDR0.00');
    expect(jSuites.mask.render(undefined, { mask: 'XDR#,##0.00;[Red]-XDR#,##0.00' }, true)).toBe('XDR0.00');
    expect(jSuites.mask.render(undefined, { mask: '0%' }, true)).toBe('0%');
    expect(jSuites.mask.render(undefined, { mask: '0.00%' }, true)).toBe('0.00%');
    expect(jSuites.mask.render(undefined, { mask: '0.00E+00' }, true)).toBe('0.00e+00');
    expect(jSuites.mask.render(undefined, { mask: '##0.0E+0' }, true)).toBe('000.0e+0');
    expect(jSuites.mask.render(undefined, { mask: '# ?/?' }, true)).toBe('0    ');
    expect(jSuites.mask.render(undefined, { mask: '# ??/??' }, true)).toBe('0      ');
    expect(jSuites.mask.render(undefined, { mask: 'dd/mm/yyyy' }, true)).toBe('00/01/1900');
    expect(jSuites.mask.render(undefined, { mask: 'dd-mmm-yy' }, true)).toBe('00-Jan-00');
    expect(jSuites.mask.render(undefined, { mask: 'dd-mmm' }, true)).toBe('00-Jan');
    expect(jSuites.mask.render(undefined, { mask: 'mmm-yy' }, true)).toBe('Jan-00');
    expect(jSuites.mask.render(undefined, { mask: 'h:mm am/pm' }, true)).toBe('12:00 am');
    expect(jSuites.mask.render(undefined, { mask: 'h:mm:ss am/pm' }, true)).toBe('12:00:00 am');
    expect(jSuites.mask.render(undefined, { mask: 'h:mm' }, true)).toBe('0:00');
    expect(jSuites.mask.render(undefined, { mask: 'h:mm:ss' }, true)).toBe('0:00:00');
    expect(jSuites.mask.render(undefined, { mask: 'dd/mm/yyyy h:mm' }, true)).toBe('00/01/1900 0:00');
    expect(jSuites.mask.render(undefined, { mask: 'mm:ss' }, true)).toBe('00:00');
    expect(jSuites.mask.render(undefined, { mask: 'mm:ss.0' }, true)).toBe('00:00.0');
    expect(jSuites.mask.render(undefined, { mask: '@' }, true)).toBe('0');
    expect(jSuites.mask.render(undefined, { mask: '[h]:mm:ss' }, true)).toBe('0:00:00');
    expect(jSuites.mask.render(undefined, { mask: '*-XDR* #,##0*-;-XDR* #,##0_-;_-XDR* "-"_-;_-@_-' }, true)).toBe(' XDR                                    -');
    expect(jSuites.mask.render(undefined, { mask: '*-* #,##0*-;-* #,##0_-;_-* "-"_-;_-@_-' }, true)).toBe('                                              -');
    expect(jSuites.mask.render(undefined, { mask: '*-XDR* #,##0.00*-;-XDR* #,##0.00_-;_-XDR* "-"??_-;_-@_-' }, true)).toBe(' XDR                                  -  ');
    expect(jSuites.mask.render(undefined, { mask: '*-* #,##0.00*-;-* #,##0.00_-;_-* "-"??_-;_-@_-' }, true)).toBe('                                            -  ');
    expect(jSuites.mask.render(undefined, { mask: '[$-en-US]h:mm:ss AM/PM' }, true)).toBe('12:00:00 AM');
    expect(jSuites.mask.render(undefined, { mask: '[$-en-001]dddd, d mmmm yyyy' }, true)).toBe('');
    expect(jSuites.mask.render(undefined, { mask: '[$-en-US]h:mm:ss am/pm' }, true)).toBe('12:00:00 AM');
});
