const jSuites = require('../dist/jsuites');

describe('jSuites mask', () => {
    describe('()', () => {
        test('basic decimals', () => {
            expect(jSuites.mask('123.456789', { mask: '00.00' }).value).toEqual('123.456789');
            expect(jSuites.mask('123.456', { mask: '00.0' }).value).toEqual('123.456');
            expect(jSuites.mask('123.456789', { mask: '00,00' }).value).toEqual('123,456789');
            expect(jSuites.mask('123.456', { mask: '00,0' }).value).toEqual('123,456');
            expect(jSuites.mask('-123.456', { mask: '00,0' }).value).toEqual('-123,456');
        });

        test('currency', () => {    
            expect(jSuites.mask("12345.678", { mask: '#,##0.00' }).value).toEqual("12,345.678");
            expect(jSuites.mask("987654.321", { mask: '#,##0.00' }).value).toEqual("987,654.321");
            expect(jSuites.mask("54321", { mask: '#,##0' }).value).toEqual("54,321");

            expect(jSuites.mask("12345.678", { mask: '#,##0.00' }).value).toEqual("12,345.678");
            expect(jSuites.mask("987654.321", { mask: '#,##0.00' }).value).toEqual("987,654.321");
            expect(jSuites.mask("11873987654.321", { mask: '#,##0.00' }).value).toEqual("11,873,987,654.321");

            expect(jSuites.mask("12345.678", { mask: '#.##0,00' }).value).toEqual("12.345,678");
            expect(jSuites.mask("987654.321", { mask: '#.##0,00' }).value).toEqual("987.654,321");
            expect(jSuites.mask("11873987654.321", { mask: '#.##0,00' }).value).toEqual("11.873.987.654,321");
            expect(jSuites.mask("11873987654", { mask: '#.##0' }).value).toEqual("11.873.987.654");

            expect(jSuites.mask("-12345.678", { mask: '#,##0.00' }).value).toEqual("-12,345.678");
            expect(jSuites.mask("-987654.321", { mask: '#,##0.00' }).value).toEqual("-987,654.321");
            expect(jSuites.mask("-11873987654.321", { mask: '#,##0.00' }).value).toEqual("-11,873,987,654.321");
            expect(jSuites.mask("-12345.678", { mask: '#.##0,00' }).value).toEqual("-12.345,678");
            expect(jSuites.mask("-987654.321", { mask: '#.##0,00' }).value).toEqual("-987.654,321");
            expect(jSuites.mask("-11873987654.321", { mask: '#.##0,00' }).value).toEqual("-11.873.987.654,321");
            expect(jSuites.mask("-11873987654", { mask: '#.##0' }).value).toEqual("-11.873.987.654");
        });

        test('scientific', () => {
            expect(jSuites.mask("100000", { mask: '0E+00' }).value).toEqual("100000");
            expect(jSuites.mask("11873987654", { mask: '0.00E+00' }).value).toEqual("11873987654");
            expect(jSuites.mask("-11873987654", { mask: '0.00E+00' }).value).toEqual("-11873987654");
        });

        test('date', () => {
            expect(jSuites.mask("20091999", { mask: 'dd/mm/yyyy' }).value).toEqual("20/09/1999");
            expect(jSuites.mask("20 09 1999", { mask: 'dd/mm/yyyy' }).value).toEqual("20/09/1999");
            expect(jSuites.mask("20 Sep 1999", { mask: 'dd/mmm/yyyy' }).value).toEqual("20/Sep/1999");
            expect(jSuites.mask("20 Sep 1999", { mask: 'dd/mon/yyyy' }).value).toEqual("20/Sep/1999");
        });
    });

    describe('fullmask', () => {
        test('integers', () => {
            expect(jSuites.mask("0", { mask: '0' }, true).value).toEqual("0");
            expect(jSuites.mask("10", { mask: '0' }, true).value).toEqual("10");
            expect(jSuites.mask("100", { mask: '0' }, true).value).toEqual("100");
            expect(jSuites.mask("-100", { mask: '0' }, true).value).toEqual("-100");
                
            expect(jSuites.mask("1000", { mask: '000000' }, true).value).toEqual("001000");
            expect(jSuites.mask("1", { mask: '000000' }, true).value).toEqual("000001");
            expect(jSuites.mask("-1", { mask: '000000' }, true).value).toEqual("-000001");
                
            expect(jSuites.mask("-10", { mask: '0' }, true).value).toEqual("-10");
            expect(jSuites.mask("-100", { mask: '0' }, true).value).toEqual("-100");
            expect(jSuites.mask("-1000", { mask: '0000' }, true).value).toEqual("-1000");
            expect(jSuites.mask("-1000", { mask: '000000' }, true).value).toEqual("-001000");
                
            expect(jSuites.mask("123456789", { mask: '0' }, true).value).toEqual("123456789");
            expect(jSuites.mask("1000000000", { mask: '0000000000' }, true).value).toEqual("1000000000");
            expect(jSuites.mask("999999999", { mask: '0000000000' }, true).value).toEqual("0999999999");
                
            expect(jSuites.mask("123", { mask: '0000' }, true).value).toEqual("0123");
            expect(jSuites.mask("12345", { mask: '00000' }, true).value).toEqual("12345");
            expect(jSuites.mask("9", { mask: '00' }, true).value).toEqual("09");
            expect(jSuites.mask("99", { mask: '00' }, true).value).toEqual("99");
        });

        test('basic decimals', () => {
            expect(jSuites.mask('1', { mask: '000000.00' }, true).value).toEqual('000001.00');
            expect(jSuites.mask('21', { mask: '000000.00' }, true).value).toEqual('000021.00');
            expect(jSuites.mask('21.123', { mask: '000000.00' }, true).value).toEqual('000021.12');

            expect(jSuites.mask('21.123', { mask: '000000' }, true).value).toEqual('000021');
            expect(jSuites.mask('-21.123', { mask: '000000' }, true).value).toEqual('-000021');
            expect(jSuites.mask('21.49', { mask: '000000' }, true).value).toEqual('000021');
            expect(jSuites.mask('21.5', { mask: '000000' }, true).value).toEqual('000022');
            expect(jSuites.mask('21.51', { mask: '000000' }, true).value).toEqual('000022');
            expect(jSuites.mask('-21.51', { mask: '000000' }, true).value).toEqual('-000022');
            expect(jSuites.mask('21.999', { mask: '000000' }, true).value).toEqual('000022');

            expect(jSuites.mask('21.123', { mask: '00.00' }, true).value).toEqual('21.12');
            expect(jSuites.mask('21.1211111111', { mask: '00.00' }, true).value).toEqual('21.12');
            expect(jSuites.mask('21.125', { mask: '00.00' }, true).value).toEqual('21.13');
            expect(jSuites.mask('21.1251', { mask: '00.00' }, true).value).toEqual('21.13');
            expect(jSuites.mask('21.129', { mask: '00.00' }, true).value).toEqual('21.13');
            expect(jSuites.mask('21.1299999999', { mask: '00.00' }, true).value).toEqual('21.13');

            expect(jSuites.mask('21.123', { mask: '00,00' }, true).value).toEqual('21,12');
            expect(jSuites.mask('21.129999', { mask: '00,00' }, true).value).toEqual('21,13');
        });

        test('scientific', () => {
            expect(jSuites.mask("100000", { mask: '0E+00' }, true).value).toEqual("1E+05");
            expect(jSuites.mask("11873987654", { mask: '0.00E+00' }, true).value).toEqual("1.19E+10");
            expect(jSuites.mask("-11873987654", { mask: '0.00E+00' }, true).value).toEqual("-1.19E+10");
            expect(jSuites.mask("0.000000123", { mask: '0.00E+00' }, true).value).toEqual("1.23E-07");
            expect(jSuites.mask("0.000456", { mask: '0.00E+00' }, true).value).toEqual("4.56E-04");
            expect(jSuites.mask("-0.000456", { mask: '0.00E+00' }, true).value).toEqual("-4.56E-04");
            expect(jSuites.mask("987654321000000", { mask: '0.00E+00' }, true).value).toEqual("9.88E+14");
            expect(jSuites.mask("-987654321000000", { mask: '0.00E+00' }, true).value).toEqual("-9.88E+14");
            expect(jSuites.mask("0", { mask: '0.00E+00' }, true).value).toEqual("0.00E+00");
            expect(jSuites.mask("123456789", { mask: '0E+00' }, true).value).toEqual("1E+08");
            expect(jSuites.mask("-123456789", { mask: '0E+00' }, true).value).toEqual("-1E+08");
            expect(jSuites.mask("0.000987", { mask: '0E+00' }, true).value).toEqual("1E-03");
            expect(jSuites.mask("-0.000987", { mask: '0E+00' }, true).value).toEqual("-1E-03");
            expect(jSuites.mask("15000", { mask: '0E+00' }, true).value).toEqual("2E+04");
            expect(jSuites.mask("-15000", { mask: '0E+00' }, true).value).toEqual("-2E+04");
            expect(jSuites.mask("0", { mask: '0E+00' }, true).value).toEqual("0E+00");
        });

        test('number + general', () => {
            expect(jSuites.mask("24", { mask: '0 liters' }, true).value).toEqual("24 liters");
            expect(jSuites.mask("24", { mask: '0 liters' }, true).value).toEqual("24 liters");
            expect(jSuites.mask("875799.99", { mask: '$ 0.00' }, true).value).toEqual("$ 875799.99");
            expect(jSuites.mask("875799.99", { mask: '$ #,##0.00' }, true).value).toEqual("$ 875,799.99");
        });

        test('date', () => {
            expect(jSuites.mask("20091999", { mask: 'dd/mm/yyyy' }, true).value).toEqual("20/09/1999");
            expect(jSuites.mask("20 09 1999", { mask: 'dd/mm/yyyy' }, true).value).toEqual("20/09/1999");
            expect(jSuites.mask("20 Sep 1999", { mask: 'dd/mmm/yyyy' }, true).value).toEqual("20/Sep/1999");
            expect(jSuites.mask("20 Sep 1999", { mask: 'dd/mon/yyyy' }, true).value).toEqual("20/Sep/1999");
            expect(jSuites.mask("20091999", { mask: 'dd/mm/yyyy' }, true).value).toEqual("20/09/1999");
            expect(jSuites.mask("20091999", { mask: 'dd-mm-yyyy' }, true).value).toEqual("20-09-1999");
            expect(jSuites.mask("20091999", { mask: 'dd.mm.yyyy' }, true).value).toEqual("20.09.1999");
            expect(jSuites.mask("20 September 1999", { mask: 'dd/mon/yyyy' }, true).value).toEqual("20/Sep/1999");
            expect(jSuites.mask("20 September 1999", { mask: 'dd mmmm yyyy' }, true).value).toEqual("20 September 1999");
            expect(jSuites.mask("200919", { mask: 'dd/mm/yy' }, true).value).toEqual("20/09/19");
            expect(jSuites.mask("200999", { mask: 'dd/mm/yy' }, true).value).toEqual("20/09/99");
            expect(jSuites.mask("2091999", { mask: 'dd/mm/yyyy' }, true).value).toEqual("20/09/1999");
            expect(jSuites.mask("200999", { mask: 'dd/mm/yyyy' }, true).value).toEqual("20/09/99");

            expect(jSuites.mask("31022020", { mask: 'dd/mm/yyyy' }, true).value).toEqual("29/02/2020");
            expect(jSuites.mask("29022020", { mask: 'dd/mm/yyyy' }, true).value).toEqual("29/02/2020");
            expect(jSuites.mask("29022019", { mask: 'dd/mm/yyyy' }, true).value).toEqual("28/02/2019");

            expect(jSuites.mask("19990920", { mask: 'yyyy/mm/dd' }, true).value).toEqual("1999/09/20");
            expect(jSuites.mask("1999 Sep 20", { mask: 'yyyy/mmm/dd' }, true).value).toEqual("1999/Sep/20");
            expect(jSuites.mask("09201999", { mask: 'mm-dd-yyyy' }, true).value).toEqual("09-20-1999");
            expect(jSuites.mask("Sep 20 1999", { mask: 'mmm/dd/yyyy' }, true).value).toEqual("Sep/20/1999");
            expect(jSuites.mask("September 20 1999", { mask: 'mmmm-dd-yyyy' }, true).value).toEqual("September-20-1999");
            expect(jSuites.mask("19992009", { mask: 'yyyy-dd-mm' }, true).value).toEqual("1999-20-09");
            expect(jSuites.mask("1999 20 Sep", { mask: 'yyyy/dd/mmm' }, true).value).toEqual("1999/20/Sep");
            expect(jSuites.mask("1999 Sep 20", { mask: 'yyyy-mmm/dd' }, true).value).toEqual("1999-Sep/20");
            expect(jSuites.mask("19992009", { mask: 'yyyy.dd-mm' }, true).value).toEqual("1999.20-09");
            expect(jSuites.mask("1999 09 20", { mask: 'yyyy.mm.dd' }, true).value).toEqual("1999.09.20");
            expect(jSuites.mask("09201999", { mask: 'mm.dd-yyyy' }, true).value).toEqual("09.20-1999");
            expect(jSuites.mask("09201999", { mask: 'mm/dd/yyyy' }, true).value).toEqual("09/20/1999");
            expect(jSuites.mask("09201999", { mask: 'mm dd yyyy' }, true).value).toEqual("09 20 1999");
            expect(jSuites.mask("200919", { mask: 'dd/mm/yy' }, true).value).toEqual("20/09/19");
            expect(jSuites.mask("09192019", { mask: 'mm/dd/yyyy' }, true).value).toEqual("09/19/2019");
            expect(jSuites.mask("091919", { mask: 'mm/dd/yy' }, true).value).toEqual("09/19/19");
            expect(jSuites.mask("Sep201999", { mask: 'mmm/dd/yyyy' }, true).value).toEqual("Sep/20/1999");
            expect(jSuites.mask("20 Sep 1999", { mask: 'dd/mmm/yyyy' }, true).value).toEqual("20/Sep/1999");
        });
    });

    describe('onkeydown single tokens', () => {
        test('0.00', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="0.00">';
            let input = document.getElementById('test-input')
            const event = new InputEvent('input', { bubbles: true, cancelable: true });

            input.value = '7581003';
            input.dispatchEvent(event);
            expect(input.value).toEqual('7581003');
            input.value = '.03';
            input.dispatchEvent(event);
            // expect(input.value).toEqual('0.03');
            input.value = '-.03';
            input.dispatchEvent(event);
            // expect(input.value).toEqual('-0,03');
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '00';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '000000000';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '01';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '00000001';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '7581003.00003';
            input.dispatchEvent(event);
            expect(input.value).toEqual('7581003.00003');
            input.value = '-7581003.00003';
            input.dispatchEvent(event);
            expect(input.value).toEqual('-7581003.00003');
            input.value = '7581003.000-03';
            input.dispatchEvent(event);
            expect(input.value).toEqual('-7581003.00003');
            input.value = '7581-003.00003';
            input.dispatchEvent(event);
            expect(input.value).toEqual('-7581003.00003');
            input.value = '123abcde';
            input.dispatchEvent(event);
            expect(input.value).toEqual('123');
            input.value = '';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('0,00', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="0,00">';
            let input = document.getElementById('test-input')
            const event = new InputEvent('input', { bubbles: true, cancelable: true });

            input.value = '7581003';
            input.dispatchEvent(event);
            expect(input.value).toEqual('7581003');
            input.value = ',03';
            input.dispatchEvent(event);
            // expect(input.value).toEqual('0,03');
            input.value = '-,03';
            input.dispatchEvent(event);
            // expect(input.value).toEqual('-0,03');
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '00';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '000000000';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '01';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '00000001';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '7581003,00003';
            input.dispatchEvent(event);
            expect(input.value).toEqual('7581003,00003');
            input.value = '-7581003,00003';
            input.dispatchEvent(event);
            expect(input.value).toEqual('-7581003,00003');
            input.value = '7581003,000-03';
            input.dispatchEvent(event);
            expect(input.value).toEqual('-7581003,00003');
            input.value = '7581-003,00003';
            input.dispatchEvent(event);
            expect(input.value).toEqual('-7581003,00003');
            input.value = '123abcde';
            input.dispatchEvent(event);
            expect(input.value).toEqual('123');
            input.value = '';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('0%', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="0%">';
            let input = document.getElementById('test-input')
            const event = new InputEvent('input', { bubbles: true, cancelable: true });

            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0%');
            input.value = '';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '7';
            input.dispatchEvent(event);
            expect(input.value).toEqual('7%');
            input.value = '54';
            input.dispatchEvent(event);
            expect(input.value).toEqual('54%');
            input.value = '100';
            input.dispatchEvent(event);
            expect(input.value).toEqual('100%');
            input.value = '100.0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('100.0%');
            input.value = '764';
            input.dispatchEvent(event);
            expect(input.value).toEqual('764%');
            input.value = '124577';
            input.dispatchEvent(event);
            expect(input.value).toEqual('124577%');
            input.value = '123abcde';
            input.dispatchEvent(event);
            expect(input.value).toEqual('123%');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('0.00%', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="0.00%">';
            let input = document.getElementById('test-input')
            const event = new InputEvent('input', { bubbles: true, cancelable: true });

            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0%');
            input.value = '';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '7';
            input.dispatchEvent(event);
            expect(input.value).toEqual('7%');
            input.value = '54';
            input.dispatchEvent(event);
            expect(input.value).toEqual('54%');
            input.value = '100';
            input.dispatchEvent(event);
            expect(input.value).toEqual('100%');
            input.value = '100.0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('100.0%');
            input.value = '764';
            input.dispatchEvent(event);
            expect(input.value).toEqual('764%');
            input.value = '124577';
            input.dispatchEvent(event);
            expect(input.value).toEqual('124577%');
            input.value = '123abcde';
            input.dispatchEvent(event);
            expect(input.value).toEqual('123%');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('#,##0.00', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="#,##0.00">';
            let input = document.getElementById('test-input')
            const event = new InputEvent('input', { bubbles: true, cancelable: true });

            input.value = '7581003';
            input.dispatchEvent(event);
            expect(input.value).toEqual('7,581,003');
            input.value = '75810.03';
            input.dispatchEvent(event);
            expect(input.value).toEqual('75,810.03');
            input.value = '9876543210';
            input.dispatchEvent(event);
            expect(input.value).toEqual('9,876,543,210');
            input.value = '1234567890.99';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1,234,567,890.99');
            input.value = '1234';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1,234');
            input.value = '100';
            input.dispatchEvent(event);
            expect(input.value).toEqual('100');
            input.value = '100.5';
            input.dispatchEvent(event);
            expect(input.value).toEqual('100.5');
            input.value = '';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '-5000';
            input.dispatchEvent(event);
            expect(input.value).toEqual('-5,000');
            input.value = '-5000.75';
            input.dispatchEvent(event);
            expect(input.value).toEqual('-5,000.75');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('#.##0,00', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="#.##0,00">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '7581003';
            input.dispatchEvent(event);
            expect(input.value).toEqual('7.581.003');
            input.value = '75810,03';
            input.dispatchEvent(event);
            expect(input.value).toEqual('75.810,03');
            input.value = '9876543210';
            input.dispatchEvent(event);
            expect(input.value).toEqual('9.876.543.210');
            input.value = '1234567890,99';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1.234.567.890,99');
            input.value = '1234';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1.234');
            input.value = '100,5';
            input.dispatchEvent(event);
            expect(input.value).toEqual('100,5');
            input.value = '';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '-5000';
            input.dispatchEvent(event);
            expect(input.value).toEqual('-5.000');
            input.value = '-5000,75';
            input.dispatchEvent(event);
            expect(input.value).toEqual('-5.000,75');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });  

        test('D', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="dd">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '4';
            input.dispatchEvent(event);
            expect(input.value).toEqual('04');
            input.value = '10';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '20';
            input.dispatchEvent(event);
            expect(input.value).toEqual('20');
            input.value = '30';
            input.dispatchEvent(event);
            expect(input.value).toEqual('30');
            input.value = '31';
            input.dispatchEvent(event);
            expect(input.value).toEqual('31');
            input.value = '32';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '36';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '1.0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '-3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('DD', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="dd">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '4';
            input.dispatchEvent(event);
            expect(input.value).toEqual('04');
            input.value = '10';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '20';
            input.dispatchEvent(event);
            expect(input.value).toEqual('20');
            input.value = '30';
            input.dispatchEvent(event);
            expect(input.value).toEqual('30');
            input.value = '31';
            input.dispatchEvent(event);
            expect(input.value).toEqual('31');
            input.value = '32';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '36';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '1.0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '-3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('DDD', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="ddd">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '4';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '10';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '20';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = 'm';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Mon');
            input.value = 't';
            input.dispatchEvent(event);
            expect(input.value).toEqual('t');
            input.value = 't abcdefgijklmnopqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('t');
            input.value = 'tu';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Tue');
            input.value = 'th';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Thu');
            input.value = 'w';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Wed');
            input.value = 'f';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Fri');
            input.value = 's';
            input.dispatchEvent(event);
            expect(input.value).toEqual('s');
            input.value = 's bcdefghijklmnopqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('s');
            input.value = 'sa';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Sat');
            input.value = 'su';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Sun');
            input.value = 'abcdeghijklnopqruvxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '-';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('DDDD', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="dddd">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '4';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '10';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '20';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = 'm';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Monday');
            input.value = 't';
            input.dispatchEvent(event);
            expect(input.value).toEqual('t');
            input.value = 't abcdefgijklmnopqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('t');
            input.value = 'tu';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Tuesday');
            input.value = 'th';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Thursday');
            input.value = 'w';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Wednesday');
            input.value = 'f';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Friday');
            input.value = 's';
            input.dispatchEvent(event);
            expect(input.value).toEqual('s');
            input.value = 's bcdefghijklmnopqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('s');
            input.value = 'sa';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Saturday');
            input.value = 'su';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Sunday');
            input.value = 'abcdeghijklnopqruvxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '-';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('DY', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="dy">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '4';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '10';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '20';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = 'm';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Mon');
            input.value = 't';
            input.dispatchEvent(event);
            expect(input.value).toEqual('t');
            input.value = 't abcdefgijklmnopqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('t');
            input.value = 'tu';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Tue');
            input.value = 'th';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Thu');
            input.value = 'w';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Wed');
            input.value = 'f';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Fri');
            input.value = 's';
            input.dispatchEvent(event);
            expect(input.value).toEqual('s');
            input.value = 's bcdefghijklmnopqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('s');
            input.value = 'sa';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Sat');
            input.value = 'su';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Sun');
            input.value = 'abcdeghijklnopqruvxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '-';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('DAY', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="day">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '4';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '10';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '20';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = 'm';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Monday');
            input.value = 't';
            input.dispatchEvent(event);
            expect(input.value).toEqual('t');
            input.value = 't abcdefgijklmnopqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('t');
            input.value = 'tu';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Tuesday');
            input.value = 'th';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Thursday');
            input.value = 'w';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Wednesday');
            input.value = 'f';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Friday');
            input.value = 's';
            input.dispatchEvent(event);
            expect(input.value).toEqual('s');
            input.value = 's bcdefghijklmnopqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('s');
            input.value = 'sa';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Saturday');
            input.value = 'su';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Sunday');
            input.value = 'abcdeghijklnopqruvxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '-';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('WD', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="wd">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '4';
            input.dispatchEvent(event);
            expect(input.value).toEqual('4');
            input.value = '6';
            input.dispatchEvent(event);
            expect(input.value).toEqual('6');
            input.value = '7';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '8';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '10';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '11';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '30';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '1.0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '-3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = 'abcdefghijklmnopqrstuvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('M', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="mm">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('02');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('03');
            input.value = '4';
            input.dispatchEvent(event);
            expect(input.value).toEqual('04');
            input.value = '10';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '11';
            input.dispatchEvent(event);
            expect(input.value).toEqual('11');
            input.value = '12';
            input.dispatchEvent(event);
            expect(input.value).toEqual('12');
            input.value = '13';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '14';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '15';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '1.0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '1,0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '-1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '-11';
            input.dispatchEvent(event);
            expect(input.value).toEqual('11');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('MM', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="mm">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('02');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('03');
            input.value = '4';
            input.dispatchEvent(event);
            expect(input.value).toEqual('04');
            input.value = '10';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '11';
            input.dispatchEvent(event);
            expect(input.value).toEqual('11');
            input.value = '12';
            input.dispatchEvent(event);
            expect(input.value).toEqual('12');
            input.value = '13';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '14';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '15';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '1.0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '1,0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '-1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '-11';
            input.dispatchEvent(event);
            expect(input.value).toEqual('11');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('MMM', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="mmm">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '11';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '99';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '111';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = 'J';
            input.dispatchEvent(event);
            expect(input.value).toEqual('J');
            input.value = 'j';
            input.dispatchEvent(event);
            expect(input.value).toEqual('j');
            input.value = 'j bcdefghijklmnopqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('j');
            input.value = 'ja';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Jan');
            input.value = 'ju';
            input.dispatchEvent(event);
            expect(input.value).toEqual('ju');
            input.value = 'jun';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Jun');
            input.value = 'jul';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Jul');
            input.value = 'f';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Feb');
            input.value = 'm';
            input.dispatchEvent(event);
            expect(input.value).toEqual('m');
            input.value = 'ma';
            input.dispatchEvent(event);
            expect(input.value).toEqual('ma');
            input.value = 'ma abcdefghijklmnopqstuvwxz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('ma');
            input.value = 'mar';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Mar');
            input.value = 'may';
            input.dispatchEvent(event);
            expect(input.value).toEqual('May');
            input.value = 'a';
            input.dispatchEvent(event);
            expect(input.value).toEqual('a');
            input.value = 'a abcdefghijklmnoqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('a');
            input.value = 'ap';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Apr');
            input.value = 'au';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Aug');
            input.value = 's';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Sep');
            input.value = 'o';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Oct');
            input.value = 'n';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Nov');
            input.value = 'd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Dec');
            input.value = 'bceghiklpqrtuvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '-';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('MMMM', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="mmmm">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '11';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '99';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '111';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = 'J';
            input.dispatchEvent(event);
            expect(input.value).toEqual('J');
            input.value = 'j';
            input.dispatchEvent(event);
            expect(input.value).toEqual('j');
            input.value = 'j bcdefghijklmnopqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('j');
            input.value = 'ja';
            input.dispatchEvent(event);
            expect(input.value).toEqual('January');
            input.value = 'ju';
            input.dispatchEvent(event);
            expect(input.value).toEqual('ju');
            input.value = 'jun';
            input.dispatchEvent(event);
            expect(input.value).toEqual('June');
            input.value = 'jul';
            input.dispatchEvent(event);
            expect(input.value).toEqual('July');
            input.value = 'f';
            input.dispatchEvent(event);
            expect(input.value).toEqual('February');
            input.value = 'm';
            input.dispatchEvent(event);
            expect(input.value).toEqual('m');
            input.value = 'ma';
            input.dispatchEvent(event);
            expect(input.value).toEqual('ma');
            input.value = 'ma abcdefghijklmnopqstuvwxz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('ma');
            input.value = 'mar';
            input.dispatchEvent(event);
            expect(input.value).toEqual('March');
            input.value = 'may';
            input.dispatchEvent(event);
            expect(input.value).toEqual('May');
            input.value = 'a';
            input.dispatchEvent(event);
            expect(input.value).toEqual('a');
            input.value = 'a abcdefghijklmnoqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('a');
            input.value = 'ap';
            input.dispatchEvent(event);
            expect(input.value).toEqual('April');
            input.value = 'au';
            input.dispatchEvent(event);
            expect(input.value).toEqual('August');
            input.value = 's';
            input.dispatchEvent(event);
            expect(input.value).toEqual('September');
            input.value = 'o';
            input.dispatchEvent(event);
            expect(input.value).toEqual('October');
            input.value = 'n';
            input.dispatchEvent(event);
            expect(input.value).toEqual('November');
            input.value = 'd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('December');
            input.value = 'bceghiklpqrtuvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '-';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('MON', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="mon">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '11';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '99';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '111';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = 'J';
            input.dispatchEvent(event);
            expect(input.value).toEqual('J');
            input.value = 'j';
            input.dispatchEvent(event);
            expect(input.value).toEqual('j');
            input.value = 'j bcdefghijklmnopqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('j');
            input.value = 'ja';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Jan');
            input.value = 'ju';
            input.dispatchEvent(event);
            expect(input.value).toEqual('ju');
            input.value = 'jun';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Jun');
            input.value = 'jul';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Jul');
            input.value = 'f';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Feb');
            input.value = 'm';
            input.dispatchEvent(event);
            expect(input.value).toEqual('m');
            input.value = 'ma';
            input.dispatchEvent(event);
            expect(input.value).toEqual('ma');
            input.value = 'ma abcdefghijklmnopqstuvwxz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('ma');
            input.value = 'mar';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Mar');
            input.value = 'may';
            input.dispatchEvent(event);
            expect(input.value).toEqual('May');
            input.value = 'a';
            input.dispatchEvent(event);
            expect(input.value).toEqual('a');
            input.value = 'a abcdefghijklmnoqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('a');
            input.value = 'ap';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Apr');
            input.value = 'au';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Aug');
            input.value = 's';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Sep');
            input.value = 'o';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Oct');
            input.value = 'n';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Nov');
            input.value = 'd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('Dec');
            input.value = 'bceghiklpqrtuvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '-';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('MONTH', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="month">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '11';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '99';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '111';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = 'J';
            input.dispatchEvent(event);
            expect(input.value).toEqual('J');
            input.value = 'j';
            input.dispatchEvent(event);
            expect(input.value).toEqual('j');
            input.value = 'j bcdefghijklmnopqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('j');
            input.value = 'ja';
            input.dispatchEvent(event);
            expect(input.value).toEqual('January');
            input.value = 'ju';
            input.dispatchEvent(event);
            expect(input.value).toEqual('ju');
            input.value = 'jun';
            input.dispatchEvent(event);
            expect(input.value).toEqual('June');
            input.value = 'jul';
            input.dispatchEvent(event);
            expect(input.value).toEqual('July');
            input.value = 'f';
            input.dispatchEvent(event);
            expect(input.value).toEqual('February');
            input.value = 'm';
            input.dispatchEvent(event);
            expect(input.value).toEqual('m');
            input.value = 'ma';
            input.dispatchEvent(event);
            expect(input.value).toEqual('ma');
            input.value = 'ma abcdefghijklmnopqstuvwxz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('ma');
            input.value = 'mar';
            input.dispatchEvent(event);
            expect(input.value).toEqual('March');
            input.value = 'may';
            input.dispatchEvent(event);
            expect(input.value).toEqual('May');
            input.value = 'a';
            input.dispatchEvent(event);
            expect(input.value).toEqual('a');
            input.value = 'a abcdefghijklmnoqrstvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('a');
            input.value = 'ap';
            input.dispatchEvent(event);
            expect(input.value).toEqual('April');
            input.value = 'au';
            input.dispatchEvent(event);
            expect(input.value).toEqual('August');
            input.value = 's';
            input.dispatchEvent(event);
            expect(input.value).toEqual('September');
            input.value = 'o';
            input.dispatchEvent(event);
            expect(input.value).toEqual('October');
            input.value = 'n';
            input.dispatchEvent(event);
            expect(input.value).toEqual('November');
            input.value = 'd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('December');
            input.value = 'bceghiklpqrtuvwxyz';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '-';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('YY', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="yy">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '99';
            input.dispatchEvent(event);
            expect(input.value).toEqual('99');
            input.value = '100';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '2024';
            input.dispatchEvent(event);
            expect(input.value).toEqual('20');
            input.value = '2.1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('21');
            input.value = '-99';
            input.dispatchEvent(event);
            expect(input.value).toEqual('99');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '-';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('YYY', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="yyy">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '4';
            input.dispatchEvent(event);
            expect(input.value).toEqual('4');
            input.value = '10';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '11';
            input.dispatchEvent(event);
            expect(input.value).toEqual('11');
            input.value = '12';
            input.dispatchEvent(event);
            expect(input.value).toEqual('12');
            input.value = '13';
            input.dispatchEvent(event);
            expect(input.value).toEqual('13');
            input.value = '14';
            input.dispatchEvent(event);
            expect(input.value).toEqual('14');
            input.value = '15';
            input.dispatchEvent(event);
            expect(input.value).toEqual('15');
            input.value = '999';
            input.dispatchEvent(event);
            expect(input.value).toEqual('999');
            input.value = '2001';
            input.dispatchEvent(event);
            expect(input.value).toEqual('200');
            input.value = '2024';
            input.dispatchEvent(event);
            expect(input.value).toEqual('202');
            input.value = '2999';
            input.dispatchEvent(event);
            expect(input.value).toEqual('299');
            input.value = '3001';
            input.dispatchEvent(event);
            expect(input.value).toEqual('300');
            input.value = '980213124124124981723987123';
            input.dispatchEvent(event);
            expect(input.value).toEqual('980');
            input.value = '20245';
            input.dispatchEvent(event);
            expect(input.value).toEqual('202');
            input.value = '202432423532';
            input.dispatchEvent(event);
            expect(input.value).toEqual('202');
            input.value = '9abcdfwerrdwef10';
            input.dispatchEvent(event);
            expect(input.value).toEqual('910');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '9.9.9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('999');
            input.value = '9,9,9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('999');
            input.value = '-';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('YYYY', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="yyyy">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '4';
            input.dispatchEvent(event);
            expect(input.value).toEqual('4');
            input.value = '10';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '11';
            input.dispatchEvent(event);
            expect(input.value).toEqual('11');
            input.value = '12';
            input.dispatchEvent(event);
            expect(input.value).toEqual('12');
            input.value = '13';
            input.dispatchEvent(event);
            expect(input.value).toEqual('13');
            input.value = '14';
            input.dispatchEvent(event);
            expect(input.value).toEqual('14');
            input.value = '15';
            input.dispatchEvent(event);
            expect(input.value).toEqual('15');
            input.value = '1999';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1999');
            input.value = '2001';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2001');
            input.value = '2024';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2024');
            input.value = '2999';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2999');
            input.value = '3001';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3001');
            input.value = '20245';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2024');
            input.value = '202432423532';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2024');
            input.value = '20abcdfwerrdwef24';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2024');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '1.9.9.9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1999');
            input.value = '1,9,9,9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1999');
            input.value = '-';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('H', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="h">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('9');
            input.value = '12';
            input.dispatchEvent(event);
            expect(input.value).toEqual('12');
            input.value = '19';
            input.dispatchEvent(event);
            expect(input.value).toEqual('19');
            input.value = '25';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2');
            input.value = '30';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '40';
            input.dispatchEvent(event);
            expect(input.value).toEqual('4');
            input.value = '90';
            input.dispatchEvent(event);
            expect(input.value).toEqual('9');
            input.value = '100';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '111';
            input.dispatchEvent(event);
            expect(input.value).toEqual('11');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '-3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '1.2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('12');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('HH', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="hh">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('03');
            input.value = '9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('09');
            input.value = '12';
            input.dispatchEvent(event);
            expect(input.value).toEqual('12');
            input.value = '1.2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('12');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '-';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('HH24', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="hh24">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('9');
            input.value = '12';
            input.dispatchEvent(event);
            expect(input.value).toEqual('12');
            input.value = '19';
            input.dispatchEvent(event);
            expect(input.value).toEqual('19');
            input.value = '25';
            input.dispatchEvent(event);
            expect(input.value).toEqual('2');
            input.value = '30';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '40';
            input.dispatchEvent(event);
            expect(input.value).toEqual('4');
            input.value = '90';
            input.dispatchEvent(event);
            expect(input.value).toEqual('9');
            input.value = '100';
            input.dispatchEvent(event);
            expect(input.value).toEqual('10');
            input.value = '111';
            input.dispatchEvent(event);
            expect(input.value).toEqual('11');
            input.value = '3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '-3';
            input.dispatchEvent(event);
            expect(input.value).toEqual('3');
            input.value = '1.2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('12');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('MI', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="mi">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '4';
            input.dispatchEvent(event);
            expect(input.value).toEqual('4');
            input.value = '5';
            input.dispatchEvent(event);
            expect(input.value).toEqual('5');
            input.value = '6';
            input.dispatchEvent(event);
            expect(input.value).toEqual('06');
            input.value = '7';
            input.dispatchEvent(event);
            expect(input.value).toEqual('07');
            input.value = '8';
            input.dispatchEvent(event);
            expect(input.value).toEqual('08');
            input.value = '9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('09');
            input.value = '51';
            input.dispatchEvent(event);
            expect(input.value).toEqual('51');
            input.value = '52';
            input.dispatchEvent(event);
            expect(input.value).toEqual('52');
            input.value = '58';
            input.dispatchEvent(event);
            expect(input.value).toEqual('58');
            input.value = '59';
            input.dispatchEvent(event);
            expect(input.value).toEqual('59');
            input.value = '5555555555555';
            input.dispatchEvent(event);
            expect(input.value).toEqual('55');
            input.value = '9999999999999999';
            input.dispatchEvent(event);
            expect(input.value).toEqual('09');
            input.value = '-1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '1.2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('12');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('SS', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="ss">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('0');
            input.value = '1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '4';
            input.dispatchEvent(event);
            expect(input.value).toEqual('4');
            input.value = '5';
            input.dispatchEvent(event);
            expect(input.value).toEqual('5');
            input.value = '6';
            input.dispatchEvent(event);
            expect(input.value).toEqual('06');
            input.value = '7';
            input.dispatchEvent(event);
            expect(input.value).toEqual('07');
            input.value = '8';
            input.dispatchEvent(event);
            expect(input.value).toEqual('08');
            input.value = '9';
            input.dispatchEvent(event);
            expect(input.value).toEqual('09');
            input.value = '51';
            input.dispatchEvent(event);
            expect(input.value).toEqual('51');
            input.value = '52';
            input.dispatchEvent(event);
            expect(input.value).toEqual('52');
            input.value = '58';
            input.dispatchEvent(event);
            expect(input.value).toEqual('58');
            input.value = '59';
            input.dispatchEvent(event);
            expect(input.value).toEqual('59');
            input.value = '5555555555555';
            input.dispatchEvent(event);
            expect(input.value).toEqual('55');
            input.value = '9999999999999999';
            input.dispatchEvent(event);
            expect(input.value).toEqual('09');
            input.value = '-1';
            input.dispatchEvent(event);
            expect(input.value).toEqual('1');
            input.value = '1.2';
            input.dispatchEvent(event);
            expect(input.value).toEqual('12');
            input.value = 'abcd';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });

        test('AM/PM', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="AM/PM">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '5';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '8';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '123456789.!@#$%^&*()-';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = 'A';
            input.dispatchEvent(event);
            expect(input.value).toEqual('A');
            input.value = 'P';
            input.dispatchEvent(event);
            expect(input.value).toEqual('P');
            input.value = 'AM';
            input.dispatchEvent(event);
            expect(input.value).toEqual('AM');
            input.value = 'PM';
            input.dispatchEvent(event);
            expect(input.value).toEqual('PM');
            input.value = 'BCDEFGHIJKLNOQRSTUVWXYZ';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = 'M';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
        });
    });

    describe('onkeydown mixed tokens', () => {
        test('$ #,##0.00', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="$ #,##0.00">';
            let input = document.getElementById('test-input')
            const event = new InputEvent('input', { bubbles: true, cancelable: true });

            input.value = '7581003';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 7,581,003');
            input.value = '75810.03';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 75,810.03');
            input.value = '9876543210';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 9,876,543,210');
            input.value = '1234567890.99';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 1,234,567,890.99');
            input.value = '1234';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 1,234');
            input.value = '100';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 100');
            input.value = '100.5';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 100.5');
            input.value = '';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 0');
            input.value = '-5000';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ -5,000');
            input.value = '-5000.75';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ -5,000.75');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ ');
        });

        test('$ #.##0,00', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="$ #.##0,00">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '7581003';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 7.581.003');
            input.value = '75810,03';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 75.810,03');
            input.value = '9876543210';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 9.876.543.210');
            input.value = '1234567890,99';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 1.234.567.890,99');
            input.value = '1234';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 1.234');
            input.value = '100,5';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 100,5');
            input.value = '';
            input.dispatchEvent(event);
            expect(input.value).toEqual('');
            input.value = '0';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ 0');
            input.value = '-5000';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ -5.000');
            input.value = '-5000,75';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ -5.000,75');
            input.value = '!@#$%^&*';
            input.dispatchEvent(event);
            expect(input.value).toEqual('$ ');
        });

        test('dd/mm/yyyy', () => {
            document.body.innerHTML = '<input id="test-input" type="text" data-mask="dd/mm/yyyy">';
            let input = document.getElementById('test-input');
            const event = new InputEvent('input', { bubbles: true, cancelable: true });
        
            input.value = '20091999';
            input.dispatchEvent(event);
            expect(input.value).toEqual('20/09/1999');
            input.value = '992003';
            input.dispatchEvent(event);
            expect(input.value).toEqual('09/09/2003');
            input.value = '9122003';
            input.dispatchEvent(event);
            expect(input.value).toEqual('09/12/2003');
            input.value = '3192003';
            input.dispatchEvent(event);
            expect(input.value).toEqual('31/09/2003');
            input.value = '31022005';
            input.dispatchEvent(event);
            expect(input.value).toEqual('31/02/2005');
            input.value = '20091';
            input.dispatchEvent(event);
            expect(input.value).toEqual('20/09/1');
        });
    });

    describe('.extract', () => {
        test('currency', () => {
            expect(jSuites.mask.render('$ 20,000.00', { mask: '$ #,##0.00' })).toEqual(20000.00)
            expect(jSuites.mask.render('20,000.00', { mask: '#,##0.00' })).toEqual(20000.00)
            expect(jSuites.mask.render('EU 20,000.00', { mask: '#,##0.00' })).toEqual(20000.00)
        });

        test('number', () => {
            expect(jSuites.mask.render('9 liters', { mask: '0 liters' })).toEqual(9)
            expect(jSuites.mask.render('1.5 liters', { mask: '0.0 liters' })).toEqual(1.5)
            expect(jSuites.mask.render('$ 1.5 in gas liters', { mask: '$ 0.0 in gas liters' })).toEqual(1.5)
        });

        test('scientific', () => {
            expect(jSuites.mask.render('1.23E+10', { mask: '0.00E+00' })).toEqual(12300000000)
            expect(jSuites.mask.render('1.23E+3', { mask: '0.00E+00' })).toEqual(1230)
            expect(jSuites.mask.render('4.5E-2', { mask: '0.00E+00' })).toEqual(0.045)
            expect(jSuites.mask.render('9E-2', { mask: '0.00E+00' })).toEqual(0.09)
            expect(jSuites.mask.render('9E+5', { mask: '0.00E+00' })).toEqual(900000)
        });

        test('percentage', () => {
            expect(jSuites.mask.render('100%', { mask: '0%' })).toEqual(1)
            expect(jSuites.mask.render('0%', { mask: '0%' })).toEqual(0)
            expect(jSuites.mask.render('50%', { mask: '0%' })).toEqual(0.5)
            expect(jSuites.mask.render('150%', { mask: '0%' })).toEqual(1.5)
            expect(jSuites.mask.render('50.50%', { mask: '0.00%' })).toEqual(0.505)
        });

        test('date', () => {
            expect(jSuites.mask.render('20/09/1999', { mask: 'dd/mm/yyyy' })).toEqual('1999-09-20 00:00:00')
            expect(jSuites.mask.render('05/09/1999', { mask: 'dd/mm/yyyy' })).toEqual('1999-09-05 00:00:00')
            expect(jSuites.mask.render('20/09/1999', { mask: 'd/mm/yyyy' })).toEqual('1999-09-20 00:00:00')
            expect(jSuites.mask.render('5/09/1999', { mask: 'd/mm/yyyy' })).toEqual('1999-09-05 00:00:00')
            expect(jSuites.mask.render('20/9/1999', { mask: 'dd/m/yyyy' })).toEqual('1999-09-20 00:00:00')
            expect(jSuites.mask.render('05/12/1999', { mask: 'dd/m/yyyy' })).toEqual('1999-12-05 00:00:00')
            expect(jSuites.mask.render('20/09/873', { mask: 'dd/mm/yyy' })).toEqual('1873-09-20 00:00:00')
            expect(jSuites.mask.render('20/09/999', { mask: 'dd/mm/yyy' })).toEqual('1999-09-20 00:00:00')
            expect(jSuites.mask.render('20/09/99', { mask: 'dd/mm/yy' })).toEqual('1999-09-20 00:00:00')
            expect(jSuites.mask.render('20/09/01', { mask: 'dd/mm/yy' })).toEqual('2001-09-20 00:00:00')
            expect(jSuites.mask.render('20/Sep/1999', { mask: 'dd/mmm/yyyy' })).toEqual('1999-09-20 00:00:00')
            expect(jSuites.mask.render('20/Jul/1999', { mask: 'dd/mmm/yyyy' })).toEqual('1999-07-20 00:00:00')
            expect(jSuites.mask.render('20/Feb/1999', { mask: 'dd/mmm/yyyy' })).toEqual('1999-02-20 00:00:00')
            expect(jSuites.mask.render('20/Dec/1999', { mask: 'dd/mmm/yyyy' })).toEqual('1999-12-20 00:00:00')
            expect(jSuites.mask.render('20/Sep/1999', { mask: 'dd/mon/yyyy' })).toEqual('1999-09-20 00:00:00')
            expect(jSuites.mask.render('20/Jul/1999', { mask: 'dd/mon/yyyy' })).toEqual('1999-07-20 00:00:00')
            expect(jSuites.mask.render('20/Feb/1999', { mask: 'dd/mon/yyyy' })).toEqual('1999-02-20 00:00:00')
            expect(jSuites.mask.render('20/Dec/1999', { mask: 'dd/mon/yyyy' })).toEqual('1999-12-20 00:00:00')
            
            expect(jSuites.mask.render('20/September/1999', { mask: 'dd/mmmm/yyyy' })).toEqual('1999-09-20 00:00:00')
            expect(jSuites.mask.render('September/20/1999', { mask: 'mmmm/dd/yyyy' })).toEqual('1999-09-20 00:00:00')
            expect(jSuites.mask.render('September, 20, 1999', { mask: 'mmmm, dd, yyyy' })).toEqual('1999-09-20 00:00:00')
            expect(jSuites.mask.render('20/July/1999', { mask: 'dd/mmmm/yyyy' })).toEqual('1999-07-20 00:00:00')
            expect(jSuites.mask.render('20/February/1999', { mask: 'dd/mmmm/yyyy' })).toEqual('1999-02-20 00:00:00')
            expect(jSuites.mask.render('20/December/1999', { mask: 'dd/mmmm/yyyy' })).toEqual('1999-12-20 00:00:00')
            expect(jSuites.mask.render('20/September/1999', { mask: 'dd/month/yyyy' })).toEqual('1999-09-20 00:00:00')
            expect(jSuites.mask.render('20/July/1999', { mask: 'dd/month/yyyy' })).toEqual('1999-07-20 00:00:00')
            expect(jSuites.mask.render('20/February/1999', { mask: 'dd/month/yyyy' })).toEqual('1999-02-20 00:00:00')
            expect(jSuites.mask.render('20/December/1999', { mask: 'dd/month/yyyy' })).toEqual('1999-12-20 00:00:00')

            expect(jSuites.mask.render('J, 20, 1999', { mask: 'MMMMM, dd, yyyy' })).toEqual('1999-01-20 00:00:00')
            expect(jSuites.mask.render('M, 20, 1999', { mask: 'MMMMM, dd, yyyy' })).toEqual('1999-03-20 00:00:00')
            expect(jSuites.mask.render('D, 20, 1999', { mask: 'MMMMM, dd, yyyy' })).toEqual('1999-12-20 00:00:00')
            expect(jSuites.mask.render('S, 20, 1999', { mask: 'MMMMM, dd, yyyy' })).toEqual('1999-09-20 00:00:00')
        });

        test('time', () => {
            expect(jSuites.mask.render('4:01:01', { mask: 'H:MI:SS' })).toEqual('1900-01-01 04:01:01')
            expect(jSuites.mask.render('11:59:33', { mask: 'H:MI:SS' })).toEqual('1900-01-01 11:59:33')
            expect(jSuites.mask.render('11:59:33', { mask: 'HH:MI:SS' })).toEqual('1900-01-01 11:59:33')
            expect(jSuites.mask.render('22:55:33', { mask: 'HH24:MI:SS' })).toEqual('1900-01-01 22:55:33')
            expect(jSuites.mask.render('02:55:33', { mask: 'HH24:MI:SS' })).toEqual('1900-01-01 02:55:33')
            expect(jSuites.mask.render('7:59 AM', { mask: 'HH12:MI AM/PM' })).toEqual('1900-01-01 07:59:00')
            expect(jSuites.mask.render('7:59 PM', { mask: 'HH12:MI AM/PM' })).toEqual('1900-01-01 19:59:00')
        });
    });
});
